- packages/style/README.md
- packages/style/components/filters/CheckboxFilter.module.scss
- packages/style/package.json
- packages/style/themes/default/_theme.template.scss
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/QueryBuilder/index.tsx
- packages/ui/src/layout/ScrollView.tsx
should be fix in ant design override
> normalize font that need to be on antd level

- packages/style/components/queryBuilder/QueryBuilder.module.scss
- packages/style/package.json
- packages/style/themes/default/_theme.template.scss
kf and cqdg uses different padding ratio
> make query builder padding customizable

- packages/style/components/queryBuilder/QueryBar.module.scss
- packages/style/components/queryBuilder/QueryPill.module.scss
- packages/style/package.json
- packages/style/themes/default/_theme.template.scss
Add more option for configuration
Enable KidsFirst design
Consider cqdg design https://www.figma.com/file/cnK68RMYFGoLbgsnCYvoo6/FerlabUI?node-id=647%3A10344
> Customize color and icon on the querybar

- packages/style/components/queryBuilder/QueryBuilder.module.scss
- packages/style/components/queryBuilder/QueryPill.module.scss
- packages/ui/src/components/QueryBuilder/QueryPill.tsx
- packages/ui/src/components/QueryBuilder/QueryValues.tsx
- packages/ui/src/components/QueryBuilder/index.tsx
- packages/ui/src/components/QueryBuilder/types.ts
- closes #SKFP-68
Fix pill expand icon at the same time. Replace "..." by the right arrow icon
- Storybook -> QueryBuilder With Show Hide Labels Enable
@francisl
> fix(hidelabel)

- packages/style/components/filters/RangeFilter.module.scss
- packages/ui/src/components/filters/RangeFilter.tsx
- packages/ui/src/components/filters/icons/BetweenOperatorIcon.tsx
- packages/ui/src/components/filters/icons/GreaterThanOperatorIcon.tsx
- packages/ui/src/components/filters/icons/GreaterThanOrEqualOperatorIcon.tsx
- packages/ui/src/components/filters/icons/LessThanOperatorIcon.tsx
- packages/ui/src/components/filters/icons/LessThanOrEqualOperatorIcon.tsx
- packages/ui/src/components/filters/icons/type.ts
- packages/ui/src/components/filters/types.ts
- storybook/stories/Components/Filters/RangeFilter.stories.tsx
- storybook/stories/Components/Filters/data.ts
- closes #54
https://oliviercperrier.github.io/ferlab-ui/?path=/story/ferlab-components-filters-rangefilter--term-filter-story-dictionary
> #54 redesign range filter

- packages/style/components/filters/CheckboxFilter.module.scss
- packages/style/components/filters/FilterContainer.module.scss
- packages/style/components/filters/RangeFilter.module.scss
- packages/style/components/filters/TextInputFilter.module.scss
- packages/ui/src/components/QueryBuilder/QueryValues.tsx
- packages/ui/src/components/QueryBuilder/types.ts
- packages/ui/src/components/filters/CheckboxFilter.tsx
- packages/ui/src/components/filters/FilterContainer.tsx
- packages/ui/src/components/filters/RangeFilter.tsx
- packages/ui/src/components/filters/TextInputFilter.tsx
- packages/ui/src/components/filters/types.ts
- storybook/stories/Components/QueryBuilder/QueryBuilder.stories.tsx
- closes: SKFP-165, SKFP-176, SKFP-164, SKFP-158, SKFP-157
> Fix qa review

- packages/style/components/sidebarMenu/SidebarMenu.module.scss
- packages/style/themes/default/_theme.template.scss
> Reduce default with of sidebar

- packages/style/Release.md
- packages/style/components/filters/RangeFilter.module.scss
- packages/style/package-lock.json
- packages/style/package.json
> Fix: remove input number controls for range filters

- package.json
- packages/style/components/labels/StatusLabel.scss
- packages/style/package.json
- packages/style/themes/default/_colors.scss
- packages/ui/package.json
- packages/ui/src/components/labels/Status.tsx
- packages/ui/tsconfig.json
- storybook/package-lock.json
- storybook/stories/Components/Labels/Status.stories.tsx
- tsconfig.json
> feat: #clin-548 new label for Status

- packages/ui/src/data/sqon/utils.ts
> CLIN-588: Add optional pivot in resolve sqon

- packages/style/package-lock.json
- packages/style/package.json
- packages/style/themes/default/_theme.template.scss
- packages/style/view/cards/v2/gridcard.module.scss
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/view/v2/GridCard.tsx
- storybook/stories/Views/v2/cards.GridCard.stories.tsx
> SJIP-96: Add new card component

- packages/style/components/labels/StatusLabel.scss
- packages/style/package.json
- closes Clin-612
Mettre couleur pour status approuver et refusé
...
> CLIN-612: Fix StatusLabel couleur

- packages/ui/package.json
- packages/ui/tsconfig.json
Target CommonJS module for Jest support.
> change typescript modules to CommonJS - fix jest support

- packages/style/view/cards/v2/gridcard.module.scss
- packages/ui/package-lock.json
- packages/ui/package.json
> Small fix gridcard footer

- packages/style/view/cards/v2/gridcard.module.scss
- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/QueryBuilder/QueryPills/BooleanQueryPill.tsx
- packages/ui/src/components/QueryBuilder/QueryPills/SetQueryPill.tsx
- packages/ui/src/components/QueryBuilder/QueryValues.tsx
- packages/ui/src/data/sqon/types.ts
- packages/ui/src/data/sqon/utils.ts
> Handle set

- packages/ui/package.json
- packages/ui/src/components/filters/CheckboxFilter.tsx
fix possibilité de rechercher par filter name
> fix checkboxfilter

- packages/ui/package.json
- packages/ui/src/components/ProTable/Header/ItemsCount/index.tsx
- packages/ui/src/components/ProTable/types.ts
ajout possibilité de formater l'affichage du total résultat protable
> ajout formatNumber protable

- packages/style/Architecture.md
Project will link to here instead of duplicating in each project
> doc: CLIN-1112 update style documentation

- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/QueryBuilder/Header/index.tsx
- packages/ui/src/components/QueryBuilder/index.tsx
- packages/ui/src/components/QueryBuilder/types.ts
- storybook/package-lock.json
- storybook/stories/Components/QueryBuilder/QueryBuilder.stories.tsx
> remove mandatory 50 char name limit for filters

- packages/ui/package.json
- packages/ui/src/components/filters/CheckboxFilter.tsx
- closes #Clin-1135
Corrige la sélection des 2 opérateur all et any en même temps
> fix checkbox filter footer operator

- packages/style/layout/ScrollContent.scss
- packages/style/package.json
> fix glitch affichage

- packages/ui/README.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/ProTable/index.tsx
- storybook/package-lock.json
- storybook/package.json
> fix: npm link and storybook issues

- packages/ui/package.json
- packages/ui/src/components/filters/CheckboxFilter.tsx
- closes CLIN-1188
mettre compatible le filtre de recherche avec le bouton tout
> fix dependence filtre et bouton tout checkbox filter

- packages/config/.husky/_/husky.sh
- packages/config/.husky/commit-msg
- packages/config/.husky/pre-commit
- packages/config/config.js
- packages/config/package-lock.json
- packages/config/package.json
- packages/config/templates/.eslintrc.json
- packages/config/templates/package.template.json
create a global, standardised, configuration for all project.
Will be installed or configured with `npx @ferlab/config`
it will
- configure husky
- configure eslint
- update package.json dependencies (get standard husky and eslint)
-
> clin-1287 global configuration

- packages/config/README.md
- packages/config/config.js
- packages/config/package.json
- packages/config/templates/commitlint.config.js
- packages/config/templates/package.template.json
> feat: CQDG-104 ferlab config add commitlint

- packages/ui/src/components/QueryBuilder/Header/Tools/EditFilterModal.tsx
- packages/ui/src/components/QueryBuilder/Header/Tools/ManageFiltersModal.tsx
- packages/ui/src/components/QueryBuilder/Header/index.tsx
- packages/ui/src/components/QueryBuilder/types.ts
> Fix edit saved filter modal title

- packages/style/components/anchorMenu/AnchorMenu.module.scss
- packages/ui/src/components/AnchorMenu/index.tsx
- storybook/stories/Components/AnchorMenu/AnchorMenu.stories.tsx
- implemented first for CQDG-34
AnchorMenu is a custom `Anchor` from antd
...
> feat: CQDG-34 add AnchorMenu

- packages/style/components/anchorMenu/AnchorMenu.module.scss
- packages/ui/Release.md
- packages/ui/package.json
- packages/ui/src/components/AnchorMenu/index.tsx
- storybook/stories/Components/AnchorMenu/AnchorMenu.stories.tsx
> feat: CQDG-34 update AnchorMenu with links props

- packages/style/components/uploadids/UploadIdsModal.module.scss
- packages/ui/src/components/UploadIds/UploadModal/index.tsx
- packages/ui/src/components/UploadIds/index.tsx
- packages/ui/src/components/UploadIds/types.ts
- closes CLIN-1297
Ajout d'un props optionnel pour définir une limite d'item a ajouter
LimiteItem = 20 Nombre Item = 20
LimiteItem 19 Nombre Item = 20
> feat: CLIN-1297 uploadId limit item

- packages/ui/Release.md
- packages/ui/package.json
- packages/ui/src/components/QueryBuilder/utils/useQueryBuilderState.tsx
- packages/ui/src/components/filters/RangeFilter.tsx
- packages/ui/src/components/filters/types.ts
- packages/ui/src/data/sqon/operators.ts
- packages/ui/src/data/sqon/utils.ts
- storybook/stories/Components/Filters/RangeFilter.stories.tsx
- closes #[3242](https://ferlab-crsj.atlassian.net/browse/FLUI-4)
Provide the ability to include items without data in quantitative researches.
> feat: FLUI-4 selection no data in range filter

- packages/style/package.json
> feat: CLIN-1297 increment version

- packages/ui/package.json
- packages/ui/src/components/filters/RangeFilter.tsx
- packages/ui/src/components/filters/types.ts
- packages/ui/src/data/sqon/utils.ts
fix translation and hiding filter name in querybar
> fix: FLUI-4 translation and hide field name

- .github/CODEOWNERS
- .github/pull_request_template.md
- packages/ui/README.md
- packages/ui/package.json
- packages/ui/src/components/QueryBuilder/QueryPills/BooleanQueryPill.tsx
- packages/ui/src/data/filters/Range.ts
- packages/ui/src/data/sqon/types.ts
- packages/ui/src/data/sqon/utils.ts
- closes #171 
Provide the ability to include items without data in quantitative researches.
> fix: FLUI-7 group no data in querybar pill

- packages/ui/src/components/filters/types.ts
Missing last commit on my last PR https://github.com/Ferlab-Ste-Justine/ferlab-ui/pull/178
> feat: SKFP-283 missing last commit about interface to type

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/QueryBuilder/QueryPills/BooleanQueryPill.tsx
- packages/ui/src/data/sqon/utils.ts
#BUG
Closes:
- https://ferlab-crsj.atlassian.net/browse/FLUI-14 
- https://ferlab-crsj.atlassian.net/browse/FLUI-16
https://user-images.githubusercontent.com/28421005/200831830-c0b6f7f5-60cc-41bb-a7b4-17f6148ad054.mov
> fix: FLUI-14 and FLUI-16 bugs

- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/QueryBuilder/Header/Tools/ManageFiltersModal.tsx
Fixes: https://ferlab-crsj.atlassian.net/browse/CLIN-1559
> fix: config context ant

- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/ProTable/index.tsx
- packages/ui/src/components/ProTable/types.ts
- storybook/stories/Components/Tables/ProTable/ProTable.stories.tsx
https://user-images.githubusercontent.com/28421005/205985037-f84388f9-32a2-4a7d-a80f-312e7ab3750a.mov
> Fix pro table types

- packages/ui/package.json
problème avec le build de 4.7.1
> fix: CLIN-000 fix build

- packages/style/Release.md
- packages/style/package.json
- packages/style/pages/variantEntity/CohortsTable.module.scss
- packages/style/pages/variantEntity/Consequences.module.scss
- packages/style/pages/variantEntity/Pathogenicity.module.scss
- packages/style/pages/variantEntity/StudiesTable.module.scss
- packages/style/pages/variantEntity/StudiesTableSummary.module.scss
- packages/style/pages/variantEntity/Summary.module.scss
- packages/style/pages/variantEntity/VariantEntity.module.scss
- packages/style/themes/default/_theme.template.scss
- packages/ui/Release.md
- packages/ui/package.json
- packages/ui/src/data/sqon/utils.ts
- packages/ui/src/pages/VariantEntity/Consequences/index.tsx
- packages/ui/src/pages/VariantEntity/Frequencies/CohortsTable/index.tsx
- packages/ui/src/pages/VariantEntity/Frequencies/StudiesTable/index.tsx
- packages/ui/src/pages/VariantEntity/Frequencies/index.tsx
- packages/ui/src/pages/VariantEntity/Pathogenicity/GeneTable/conditions/OmimConditionCell.tsx
- packages/ui/src/pages/VariantEntity/Pathogenicity/GeneTable/index.tsx
- packages/ui/src/pages/VariantEntity/Summary/index.tsx
- packages/ui/src/pages/VariantEntity/index.tsx
- packages/ui/src/pages/VariantEntity/types.ts
- storybook/stories/Pages/VariantEntity/VariantEntity.stories.tsx
- closes #[SKFP-554](https://d3b.atlassian.net/browse/SKFP-554)
Plusieurs fixes mineurs à la page VariantEntity: surtout des ajustements au niveau du style et du dictionnaire.
[PR KF](https://github.com/kids-first/kf-portal-ui/pull/3620)
Avant:
Après:
> 🐛fix(variant): SKFP-554 Variant entity page adjustments

- packages/ui/package.json
Don't code with covid kids, I re-added missing simplebar-react
> 🐛fix(package): re-add missing package

- packages/ui/package.json
- packages/ui/src/pages/VariantEntity/Summary/index.tsx
- closes #[574](https://d3b.atlassian.net/browse/SKFP-574)
Missed clinvar
@kstonge
> 🐛fix(page): SKFP-574 fix clinvar string formatting

- packages/ui/package.json
- packages/ui/src/pages/VariantEntity/Pathogenicity/ClinvarTable/index.tsx
- closes #[581](https://d3b.atlassian.net/browse/SKFP-581)
> 🐛fix(page): SKFP-574 fix clinvar interpretation string formatting

- packages/ui/package.json
- packages/ui/src/utils/numberUtils.test.ts
- packages/ui/src/utils/numberUtils.ts
- Ajout de tests pour les fonctions dans numberUtils.ts
> Feat: Add tests for numberUtils

- packages/ui/package.json
- packages/ui/src/pages/VariantEntity/Consequences/index.tsx
- packages/ui/src/pages/VariantEntity/Pathogenicity/ClinvarTable/index.tsx
- packages/ui/src/pages/VariantEntity/Pathogenicity/GeneTable/conditions/CosmicConditionCell.tsx
- packages/ui/src/pages/VariantEntity/Pathogenicity/GeneTable/conditions/DddConditionCell.tsx
- packages/ui/src/pages/VariantEntity/Pathogenicity/GeneTable/conditions/HpoConditionCell.tsx
- packages/ui/src/pages/VariantEntity/Pathogenicity/GeneTable/conditions/OmimConditionCell.tsx
- packages/ui/src/pages/VariantEntity/Pathogenicity/GeneTable/conditions/OrphanetConditionCell.tsx
- packages/ui/src/pages/VariantEntity/Summary/index.tsx
- packages/ui/src/utils/stringUtils.ts
- closes #[581](https://d3b.atlassian.net/browse/SKFP-581)
- closes #[576](https://d3b.atlassian.net/browse/SKFP-576)
- closes #[578](https://d3b.atlassian.net/browse/SKFP-578)
- 
After re-evaluation, after remove underscore for space, string should be in title case
Gene Consequence have also been set to title case
@kstonge
> ✨feat(variant): SKFP-574 formalize to title case

- packages/ui/Release.md
- packages/ui/jest.config.ts
- packages/ui/package.json
- packages/ui/src/components/QueryBuilder/QueryPills/BooleanQueryPill.tsx
- packages/ui/src/components/QueryBuilder/QueryPills/UploadedListQueryPill.test.tsx
- packages/ui/src/components/QueryBuilder/QueryPills/UploadedListQueryPill.tsx
- packages/ui/src/components/QueryBuilder/icons/ElementOperator.tsx
- packages/ui/src/components/QueryBuilder/utils/useQueryBuilderState.tsx
- packages/ui/src/data/sqon/types.ts
- packages/ui/src/data/sqon/utils.test.ts
- packages/ui/src/data/sqon/utils.ts
- packages/ui/src/mocks/valueContentMock.ts
- packages/ui/src/mocks/valueFilterMock.ts
- closes [SKFP-547](https://d3b.atlassian.net/browse/SKFP-547)
- Ajout d'une QueryPill pour gérer les uploaded lists + tests
> ✨feat(queryPill): SKFP-547 Uploaded List QueryPill 

- packages/style/Release.md
- packages/style/components/filters/ToggleFilter.module.scss
- packages/style/package.json
- packages/ui/Release.md
- packages/ui/package.json
- packages/ui/src/components/filters/ToggleFilter.tsx
- closes [SKFP-597](https://d3b.atlassian.net/browse/SKFP-597)
Ajustement du style/positionnement pour les ToggleFilters
> ✨feat(facets): SKFP-597 Adjust clear button for boolean facets

- packages/style/Release.md
- packages/style/package.json
- packages/style/pages/EntityPage/EntityTable.module.scss
- packages/ui/Release.md
- packages/ui/package.json
- packages/ui/src/pages/EntityPage/EntityDescriptions/index.tsx
- packages/ui/src/pages/EntityPage/EntityPage.tsx
- packages/ui/src/pages/EntityPage/EntityTableMultiple/index.tsx
- packages/ui/src/pages/EntityPage/EntityTitle/index.tsx
- packages/ui/src/pages/EntityPage/index.tsx
- closes #3242
implement EntityTableMultiple on EntityPage to handle 2 Tables by row
@luclemo
> feat: CQDG-31 implement EntityTableMultiple on EntityPage

- packages/ui/src/components/filters/RangeFilter.tsx
- closes #CLIN-1711
Can apply 0 as minimum value in RangeFilter
> fix: CLIN-1711 allow 0 as minimum value

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/ProTable/types.ts
- closes [SJIP-351](https://d3b.atlassian.net/browse/SJIP-351)
- Allow elements to be passed as Protable titles
- Update ferlab/style peerDependency version
> fix: SJIP-351 Change title type for protable columns

- packages/style/package.json
- packages/style/pages/EntityPage/EntityGeneConsequenceSubtitle.module.scss
- packages/ui/package.json
- packages/ui/src/pages/EntityPage/EntityGeneConsequence/index.tsx
> fix(entity): SKFP-618 fix visual

- packages/ui/package.json
- packages/ui/src/components/ProTable/ColumnSelector/index.tsx
- closes #222 
Fix ordering issue with multiple unordered fixed columns in protable
> Fix/fl UI 33 fix protable ordering reset

- packages/ui/Release.md
- packages/ui/package.json
- packages/ui/src/components/ProTable/ColumnSelector/index.tsx
- packages/ui/src/components/ProTable/index.tsx
- closes https://ferlab-crsj.atlassian.net/browse/FLUI-33
fix 500 error and reset button
> fix: FLUI-33 fix issue with reset columns 500

- .github/workflows/storybook.yml
- storybook/tsconfig.json
- closes FLUI-40
Fix storybook deployment
> fix: FLUI-40 storybook deployment

- packages/ui/Release.md
- packages/ui/package.json
- packages/ui/src/components/QueryBuilder/QueryPills/RemoteComponentQueryPill.tsx
- packages/ui/src/components/QueryBuilder/QueryValues.tsx
- closes [SKFP-628](https://d3b.atlassian.net/browse/SKFP-628)
- Remove brackets around values in query pill with remote component (keep them for range operator only)
> 🐛fix: SKFP-628 Remove brackets from query values

- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/ColorTag/index.module.scss
- packages/ui/src/components/ColorTag/index.test.tsx
- packages/ui/src/components/ColorTag/index.tsx
- packages/ui/themes/default/_colors.scss
- packages/ui/themes/default/_theme.template.scss
- storybook/stories/Components/ColorTag/ColorTag.stories.tsx
- closes #[650](https://d3b.atlassian.net/browse/SKFP-650)
En se référant aux specs, on remarque que plusieurs valeurs spécifiques ont un style unique (e.g. female, male etc.). Afin d'éviter une copie du code et des styles, le componenet `ColorTag` a été ajouté. Il s'agit d'un mapping de classe CSS.
Source https://www.figma.com/file/baxEfYnqjk3d87iQAPEz8S/Pages-Entit%C3%A9s?node-id=162%3A26634&t=Zcqgj8QxBanlHJA3-0
Il suffit de passer le type ainsi que la valeur afin de l'utiliser. On peut aussi y ajouter un children afin de personalisé l'affichage.
e.g. `<ColorTag type={ColorTagType.Boolean} value="true"><>Affichage custom</></ColorTag>`. 
Les couleurs peuvent être personalisé dans le fichier des themes.
> feat(colortag): SKFP-403 add a generic ColorTag

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
> fix: CLIN-1663 500 error when bad formatted json

- packages/ui/package.json
- packages/ui/tsconfig.json
Ajoute sourceMap dans le compilateur sinon les fichiers ne sont pas généré du côté de ma machine
> chore(build): SKFP-403 fix map source files build

- packages/ui/package.json
- packages/ui/src/components/AnchorMenu/index.tsx
- storybook/stories/Components/AnchorMenu/AnchorMenu.stories.tsx
- closes #[403](https://d3b.atlassian.net/browse/SKFP-403)
Ajouter la possibilité de cacher certains liens des anchors links selon le contexte.
```typescript
const links: IAnchorLink[] = [
{ href: `#${SectionId.SUMMARY}`, title: intl.get('screen.participantEntity.summary.title') },
{ href: `#${SectionId.PROFIL}`, title: intl.get('screen.participantEntity.profile.title') },
{
href: `#${SectionId.FAMILY}`,
title: intl.get('screen.participantEntity.family.title'),
hidden: !data?.families_id && totalFamilyMembers <= MIN_FAMILY_NUMBER,
},
{
href: `#${SectionId.DIAGNOSIS}`,
title: intl.get('screen.participantEntity.diagnosis.title'),
},
{
href: `#${SectionId.PHENOTYPE}`,
title: intl.get('screen.participantEntity.phenotype.title'),
},
// { href: `#${SectionId.BIOSPECIMEN}`, title: …
```
> feat(anchor): SKFP-403 add a hidden properties for anchor links

- packages/ui/package.json
- packages/ui/src/components/ProTable/Header/SelectedCount/index.test.tsx
- packages/ui/src/components/ProTable/Header/SelectedCount/index.tsx
- closes CLIN-1715
le component `SelectedCount` n'avait pas l'option d'afficher le nombre d'item sélectionner avec le formatage voulu
> fix: CLIN-1715 ajout formatNumber selectedCount

- packages/ui/package.json
- packages/ui/src/components/filters/CheckboxFilter.module.scss
- packages/ui/src/components/filters/CheckboxFilter.tsx
- packages/ui/src/components/filters/FilterContainer.tsx
- packages/ui/src/components/filters/types.ts
> fix: CLIN-1781 fix checkbox

- packages/ui/package.json
- packages/ui/tsconfig.json
> fix(build): fix build issue

- packages/ui/package.json
- packages/ui/tsconfig.json
> fix: build npm

- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/tsconfig.json
fix broken test
node don't support es module, need eject in all portal first
> fix: FLUI-000 revert to commonjs for node test

- packages/ui/package-lock.json
- packages/ui/package.json
add 'at your own risk' support for react 18.x.x
> fix: FLUI-000 add support for react 18.x.x

- packages/ui/package.json
- packages/ui/src/components/filters/CheckboxFilter/CheckboxFilter.tsx
- packages/ui/src/components/filters/FilterContainer.tsx
- packages/ui/src/components/filters/FilterSelector.tsx
- packages/ui/src/components/filters/RangeFilter.module.scss
- packages/ui/src/components/filters/RangeFilter.tsx
- packages/ui/src/components/filters/types.ts
- storybook/stories/Components/Filters/CheckboxFilter.stories.tsx
- storybook/stories/Components/Filters/RangeFilter.stories.tsx
> fix: CLIN-1809 fix no data

- packages/ui/package.json
- packages/ui/src/pages/EntityPage/EntityTable/index.module.scss
> feat: CQDG-198 add gap to EntityTable

- package-lock.json
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/layout/ResizableGridLayout/ResizableItemSelector/index.module.scss
- packages/ui/src/layout/ResizableGridLayout/ResizableItemSelector/index.tsx
- packages/ui/src/layout/ResizableGridLayout/index.module.scss
- packages/ui/src/layout/ResizableGridLayout/index.test.tsx
- packages/ui/src/layout/ResizableGridLayout/index.tsx
- packages/ui/src/view/v2/GridCard/GridCard.tsx
- packages/ui/src/view/v2/GridCard/GridCardHeader/GridCardHeader.module.scss
- packages/ui/src/view/v2/GridCard/GridCardHeader/index.tsx
- packages/ui/src/view/v2/GridCard/Gridcard.module.scss
- packages/ui/src/view/v2/GridCard/index.tsx
- storybook/stories/Layout/ResizableGridLayout.module.scss
- storybook/stories/Layout/ResizableGridLayout.stories.tsx
- closes #[664](https://d3b.atlassian.net/browse/SKFP-664)
Lire la documentation https://www.notion.so/ferlab/ResizableGridLayout-f38c403926a94daaaf7296e7325739f1
Il s'agit d'une première implémentation d'un système de grille avec la possibilité de redimensionner des cartes. On peut
- Redimensionner une carte
- Déplacer une carte
- Sauvegarder la config côté client (PR KF a venir)
- Cacher/afficher des graphiques. (À noter que afficher/cacher une carte ne la replace pas à l'endroit que l'on veut, ça vient du fait qu'on devrait calculer manuellement les positions de chaques cartes si on essait de remettre, on garde ce comportement pour la v1)
Exemple de fichiers de config utilisé
```typescript
export const getDefaultLayouts = (): IResizableGridLayoutConfig[] => [
{
title: …
```
> feat(grid): SKFP-664 add a resizable grid view

- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/layout/ResizableGridLayout/index.module.scss
- packages/ui/src/layout/ResizableGridLayout/index.test.tsx
- packages/ui/src/layout/ResizableGridLayout/index.tsx
- packages/ui/src/view/v2/GridCard/GridCardHeader/GridCardHeader.module.scss
- packages/ui/src/view/v2/GridCard/Gridcard.module.scss
- closes #[664](https://d3b.atlassian.net/browse/SKFP-664)
- Charge correctement la bonne largeur du parent lors du premier changement
- Retirer la marge des côtés de la grille
- Diminue la grandeur des headers
> fix(grid): SKFP-664 fix gridcard and default grid width

- packages/ui/package.json
- packages/ui/src/components/Assignments/AssignmentsSelect/index.module.scss
- packages/ui/src/components/Assignments/AssignmentsSelect/index.test.tsx
- packages/ui/src/components/Assignments/AssignmentsSelect/index.tsx
- packages/ui/src/components/Assignments/AssignmentsTag/index.module.scss
- packages/ui/src/components/Assignments/AssignmentsTag/index.test.tsx
- packages/ui/src/components/Assignments/AssignmentsTag/index.tsx
- packages/ui/src/components/Assignments/types.ts
- storybook/stories/Components/Assignment/AssignmentSelect.stories.tsx
- storybook/stories/Components/Assignment/AssignmentTag.stories.tsx
- closes CLIN-1769 et CLIN-1771
Première phase de développement pour le component du select des assignations et des tags pour les assignations
> feat: CLIN-1763 ajout assignation tag et select

- packages/ui/package.json
- packages/ui/src/components/Assignments/AssignmentsSelect/index.module.scss
- packages/ui/src/components/Assignments/AssignmentsSelect/index.tsx
- packages/ui/src/components/Assignments/types.ts
- packages/ui/src/components/Assignments/utils.tsx
Ajout des traductions et problème avec le autocomplete
- CLIN-1771
> fix: CLIN-1771 missing translation and autocomplete

- packages/ui/package.json
- packages/ui/src/components/Assignments/AssignmentsSelect/index.tsx
- packages/ui/src/components/Assignments/AssignmentsTag/index.tsx
- packages/ui/src/components/Assignments/types.ts
- closes #CLIN-1803
-Ajout  userAvatar dans les assignation
-Ajout traduction manquante
-Fix petit glitch
[JIRA LINK]
...
> fix: clin-1803 userAvatar et traduction

- packages/ui/package.json
- packages/ui/src/components/Assignments/AssignmentsFilter/index.tsx
- packages/ui/src/components/Assignments/AssignmentsSelect/index.tsx
- closes #CLIN-1763
Traduction manquante assignation
[JIRA LINK]
...
> fix:CLIN-1763 traduction

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/ProTable/Header/ItemsCount/index.tsx
- closes #286 
[FLUI-65](https://ferlab-crsj.atlassian.net/browse/FLUI-65)
> fix(itemsCount): FLUI-65 format number in items count

- packages/ui/package.json
- packages/ui/src/components/Assignments/AssignmentsSelect/index.module.scss
- packages/ui/src/components/Assignments/AssignmentsSelect/index.tsx
- closes #CLIN-1769
Ajout loading sur l'ajout d'une assignation
[JIRA LINK]
...
> fix: CLIN-1769 ajout loading

- .github/workflows/publish_npm.yml
- packages/ui/package.json
- closes #FLUI-75
https://ferlab-crsj.atlassian.net/browse/FLUI-75
> feat: FLUI-75 automatic npmjs release

- packages/ui/README.md
> doc: flui-0000 antd update new procedure

- .github/workflows/publish_npm.yml
> fix: FLUI-75 automatic npmjs release update

- .github/workflows/release.yml
- packages/ui/package.json
> feat: FLUI-75 automatic npmjs release 6

- .github/workflows/release.yml
- packages/ui/package.json
> feat: FLUI-75 automatic npmjs release 7

- .github/workflows/release.yml
- packages/ui/package.json
correctif publication npm automatique
> feat: FLUI-75 automatic npmjs release 8

- .github/workflows/release.yml
> feat: FLUI-75 automatic npmjs release 9

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/layout/ResizableGridLayout/ResizableGridCard/index.module.scss
- packages/ui/src/layout/ResizableGridLayout/ResizableGridCard/index.tsx
- packages/ui/src/layout/ResizableGridLayout/index.tsx
- packages/ui/src/view/v2/GridCard/GridCardHeader/index.tsx
- closes #[672](https://d3b.atlassian.net/browse/SKFP-672)
- closes #[675](https://d3b.atlassian.net/browse/SKFP-675)
SKFP-672 - Si on change la config, l'utilisateur pouvait toujours utiliser la configuration précédent sauf s'il appuyait sur le bouton reset. Un premier fix a été fait afin de permettre que si une nouvelle config par défaut est défini, certains de ces paramètres peuvent être pris en priorité (comme isResizable, static, minH et minW). Sans que le système soit parfait, il permet un peu plus de souplesse sans forcer un reset de la config utilisateur
A noter que dans la vidéo, les éléments ne ce replace pas a leur élément de base. Malheureusement, il s'agit du comportement de react-grid-layout par défaut.
SKFP-675 - Ajout du bouton close sur les cartes.
Afin de migrer vers …
> Fix/skfp 672 678/summary

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/Assignments/AssignmentsFilter/index.module.scss
- packages/ui/src/components/Assignments/AssignmentsSelect/index.module.scss
- packages/ui/src/components/Assignments/AssignmentsSelect/index.tsx
- packages/ui/src/components/Assignments/AssignmentsTag/index.module.scss
- packages/ui/src/components/Assignments/AssignmentsTag/index.tsx
- closes #CLIN-1763
_[[JIRA LINK]](https://ferlab-crsj.atlassian.net/browse/CLIN-1763)_
...
> fix: CLIN-1763 ajustement

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/QueryBuilder/utils/useQueryBuilderState.tsx
- closes #CLIN-1767
Ajout d'un fonction pour update de query avec l'option de filtre d'un tableau
[[JIRA LINK]](https://ferlab-crsj.atlassian.net/browse/CLIN-1767)
...
> feat: CLIN-1767 ajout updateQueryByFilter

- packages/ui/Release.md
- packages/ui/package.json
- packages/ui/src/layout/ResizableGridLayout/ResizableItemSelector/index.tsx
- packages/ui/src/layout/ResizableGridLayout/index.tsx
[[JIRA LINK]](https://ferlab-crsj.atlassian.net/browse/CQDG-32)
...
> feat: CQDG-32 add dictionary field to ResizableItemSelector

- packages/ui/Release.md
- packages/ui/package.json
- packages/ui/src/layout/ResizableGridLayout/index.tsx
> feat: CQDG-32 update title field translation from defaultLayouts in resizableGridLayout

- packages/ui/Release.md
- packages/ui/package.json
- packages/ui/src/components/Charts/Bar/index.tsx
Format number by locale
[[JIRA LINK]](https://ferlab-crsj.atlassian.net/browse/CQDG-280)
...
> feat: CQDG-280 update numberWithCommas by numberFormat in BarChart

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/pages/EntityPage/EntityDataset/index.module.scss
- packages/ui/src/pages/EntityPage/EntityDataset/index.test.tsx
- packages/ui/src/pages/EntityPage/EntityDataset/index.tsx
- packages/ui/src/pages/EntityPage/EntityDescriptions/index.module.scss
- packages/ui/src/pages/EntityPage/index.tsx
- storybook/stories/Pages/EntityPage/EntityDataset.stories.tsx
[[JIRA LINK]](https://ferlab-crsj.atlassian.net/browse/CQDG-305)
...
> feat: CQDG-305 implement EntityDataset for Entity Study page

- packages/ui/package.json
- packages/ui/src/pages/EntityPage/EntityDataset/index.module.scss
- packages/ui/src/pages/EntityPage/EntityDescriptions/index.module.scss
> feat: CQDG-305 fix design

- packages/ui/Release.md
- packages/ui/package.json
- packages/ui/src/components/Charts/Pie/index.tsx
[[JIRA LINK]](https://ferlab-crsj.atlassian.net/browse/CQDG-280)
...
> feat: CQDG-280 replace numberWithCommas by numberFormat in PieChart

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/List/ListItemWithActions.tsx
- storybook/stories/Components/List/ListItemWithActions.stories.tsx
[SJIP-570](https://d3b.atlassian.net/browse/SJIP-570)
To implement biospecimen request in Include I need another action to share a link.
And Lucas asks to change all action icons to outlined.
> feat(list item): SJIP-570 add action to list item

- packages/ui/package.json
- packages/ui/src/pages/EntityPage/type.ts
- closes #FLUI-83
FLUI-83 add types to IVariantEnetityDictionary to reflect received data
> fix: FLUI-83 add types to IVariantEnetityDictionary to reflect received

- packages/ui/Release.md
- packages/ui/package.json
- packages/ui/src/components/ProTable/Pagination/index.tsx
- packages/ui/src/components/ProTable/Pagination/utils.ts
- packages/ui/src/components/ProTable/types.ts
#FEAT: Ajout custom Pagination ProTable
- closes #CLIN-2197
Permettre d'avoir des options de pagination différente de celle par defaut
[[JIRA LINK]](https://ferlab-crsj.atlassian.net/browse/CLIN-2197)
Sans customPagination
Avec CustomPagination
...
> feat: CLIN-2197 ajout custom pagination

- packages/ui/Release.md
- packages/ui/package.json
- packages/ui/src/components/tables/ExpandableTable/index.tsx
- packages/ui/src/pages/EntityPage/EntityConditionsCell/HpoConditionCell.tsx
https://ferlab-crsj.atlassian.net/browse/CQDG-135
...
> feat: CQDG-135 Add dictionnary in HpoConditionCell and getColumnTitleOrTooltip in ExpandableTable

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/List/ListItemWithActions.module.scss
[SJIP-574](https://d3b.atlassian.net/browse/SJIP-574)
Update hover background color on all action button in list item component.
> fix(listitem): SJIP-574 fix button style

- packages/ui/Release.md
- packages/ui/package.json
- packages/ui/src/components/Consequences/Cell/index.tsx
- closes #[850](https://d3b.atlassian.net/browse/SKFP-850)
> fix(consequence): SKFP-850 add NO_GENE export

- packages/ui/Release.md
- packages/ui/package.json
- packages/ui/src/layout/ResizableGridLayout/ResizableGridCard/index.tsx
- packages/ui/src/layout/ResizableGridLayout/index.test.tsx
- packages/ui/src/layout/ResizableGridLayout/index.tsx
Dans certains cas, ils sembleraient que react-grid-layout entre dans une sorte de boucle infini entre un changement de 2 breakpoint. J'ai ajouté une protection afin d'éviter ce cas et de réduire nos appels à l'api. 
https://github.com/Ferlab-Ste-Justine/ferlab-ui/assets/65532894/20b33ebb-b6f4-4e9c-904d-05e2318b76d8
https://github.com/Ferlab-Ste-Justine/ferlab-ui/assets/65532894/e2beab87-73ef-4710-9fd6-1c099a0afae9
> fix(summary): SKFP-852 fix infinite loop use case

- packages/ui/Release.md
- packages/ui/package.json
- packages/ui/src/layout/ResizableGridLayout/index.test.tsx
- packages/ui/src/layout/ResizableGridLayout/index.tsx
Should fix a corrumpted config (missing base)
[JIRA LINK]
https://github.com/Ferlab-Ste-Justine/ferlab-ui/assets/65532894/5b288a41-142d-4d5a-80d5-f8aec5e13c26
https://github.com/Ferlab-Ste-Justine/ferlab-ui/assets/65532894/39dfbdab-e43a-4480-a5f9-d3a55b28514f
> fix(summary): SKFP-852 fix missing base object in config

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/layout/ResizableGridLayout/index.tsx
- packages/ui/src/layout/ResizableGridLayout/utils.ts
Dans certain cas spécifique, si l'utilisateur ouvre pour la premiere fois la page summary,  la config peut se corrompte a cause du changement de breaking point. On s'assure donc de créer la config dans ce cas.
Aussi afin d'éviter la duplication de code, une config de base par type de graphique est maintenant mis a disposition.
> fix(summary): SKFP-852 fix first time opening summary page

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/layout/ResizableGridLayout/index.tsx
- packages/ui/src/layout/ResizableGridLayout/utils.ts
Show/hide a graph make them resize to 1x1 and ignore minW and minH.
https://github.com/Ferlab-Ste-Justine/ferlab-ui/assets/65532894/b030062e-963c-4042-80fc-e9c1e294c464
https://github.com/Ferlab-Ste-Justine/ferlab-ui/assets/65532894/2f322911-beaa-4da9-b6d2-d2bfa889124a
> fix(grid): SKFP-852 cannot make baby graph anymore

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/layout/ResizableGridLayout/index.tsx
- packages/ui/src/layout/ResizableGridLayout/utils.ts
- closes #[664](https://d3b.atlassian.net/browse/SJIP-664)
Typo dans la config des grid, xss devrait etre xxs
> fix(grid): SJIP-664 fix typo in params

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
Pipeline has broke while trying to deploie previous version, this is just a quick fix
> fix(grid): SJIP-664 workaround pipeline

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/Consequences/Cell/index.module.scss
- packages/ui/src/components/Consequences/Cell/index.test.tsx
- packages/ui/src/components/Consequences/Cell/index.tsx
- packages/ui/src/components/Gene/Cell/index.test.tsx
- packages/ui/src/components/Gene/Cell/index.tsx
[SKFP-880](https://d3b.atlassian.net/browse/SKFP-880)
- Display aa_change in consequence cell and adjust size of column
- fix regression for no gene in gene cell
...
> feat(variants): SKFP-880 fix csq and gene cells

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/AuthorizedStudies/AuthorizedStudiesListItem.tsx
- packages/ui/src/components/AuthorizedStudies/index.module.scss
- packages/ui/src/components/AuthorizedStudies/index.tsx
[SKFP-918](https://d3b.atlassian.net/browse/SKFP-918)
> fix(widget): SKFP-918 auth studies style and count

- .github/workflows/npm_release_cadidate.yml
- .github/workflows/storybook.yml
- .github/workflows/uilinter.yml
- closes #FLUI-104
[[JIRA LINK]](https://ferlab-crsj.atlassian.net/jira/software/c/projects/FLUI/boards/7?selectedIssue=FLUI-104)
1. separer les githubs actions build et publish pour le storybook
2. mettre le build sur tout les pr pour valider que ok
3. garder le publish seulement sur merge
Check if the only the build is triggered in PR and if the deploy is triggered when it's merged
...
> ci(storybook): FLUI-104 split storybook build and deploy jobs

- packages/ui/package-lock.json
- packages/ui/package.json
> chore: update version

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/Widgets/Cavatica/CavaticaAnalyse.test.tsx
- packages/ui/src/components/Widgets/Cavatica/CavaticaAnalyse.tsx
- packages/ui/src/components/Widgets/Cavatica/CavaticaListItem.tsx
- packages/ui/src/pages/EntityPage/EntityTableRedirectLink/index.tsx
- closes #895
[[JIRA LINK]](https://d3b.atlassian.net/browse/SKFP-895)
> fix(SKFP-895): reset errors on close modal

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/Widgets/Cavatica/CavaticaAnalyse.test.tsx
- packages/ui/src/components/Widgets/Cavatica/CavaticaAnalyse.tsx
> chore(update): SKFP-895 port 7.20.1 to v8

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/Widgets/Cavatica/CavaticaCreateProjectModal.tsx
- closes #895
https://d3b.atlassian.net/browse/SKFP-895
Form was resetted before being submitted
> fix(SKFP-895): fix form submit issue

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/Widgets/Cavatica/CavaticaAnalyse.test.tsx
- packages/ui/src/components/Widgets/Cavatica/CavaticaAnalyse.tsx
- packages/ui/src/components/Widgets/Cavatica/CavaticaAnalyseModal.test.tsx
- packages/ui/src/components/Widgets/Cavatica/CavaticaAnalyzeModal.tsx
- closes #895
Add bulk import submit
> fix(SKFP-895): fix bulk import

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/Widgets/Cavatica/CavaticaAnalyzeModal.tsx
- closes #934
Fix wording
[[JIRA LINK](https://d3b.atlassian.net/browse/SKFP-934)]
> fix: SKFP-934 fix ok button text on cavatica analyse modal

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/Widgets/Cavatica/CavaticaAnalyse.tsx
- closes [#FLUI-121](https://ferlab-crsj.atlassian.net/jira/software/c/projects/FLUI/boards/7?selectedIssue=FLUI-121)
> feat: FLUI-121 add disable tooltip on cavatica button

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/pages/EntityPage/EntityPublicCohortTable/index.tsx
- packages/ui/src/pages/EntityPage/type.ts
- packages/ui/src/pages/EntityPage/utils/frequencies.tsx
- storybook/stories/Pages/EntityPage/EntityPublicCohortTable.stories.tsx
- closes [#FLUI-122](https://ferlab-crsj.atlassian.net/jira/software/c/projects/FLUI/boards/7?selectedIssue=FLUI-122)
> feat: FLUI-122 update public cohort table to use new types

- packages/ui/Release.md
- packages/ui/jest.setup.js
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/themes/override/main.scss
https://d3b.atlassian.net/browse/SKFP-895
> fix(modal): SKFP-895 remove color override of modal

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/pages/EntityPage/EntityNestedTable/index.module.scss
- packages/ui/src/pages/EntityPage/EntityNestedTable/index.tsx
- packages/ui/src/utils/stringUtils.test.ts
- storybook/package-lock.json
- storybook/stories/Pages/EntityPage/EntityNestedTable.stories.tsx
[SKFP-901](https://d3b.atlassian.net/browse/SKFP-901)
- Create nested table component
> feat(variant): SKFP-901 add nested table

- packages/ui/Release.md
- packages/ui/package.json
- packages/ui/src/components/ProTable/index.tsx
- packages/ui/src/components/ProTable/types.ts
- closes CLIN-2300
[JIRA LINK](https://ferlab-crsj.atlassian.net/browse/CLIN-2300)
...
> fix: CLIN-2300 disable export tsv button when total is 0

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/Consequences/Cell/index.module.scss
- packages/ui/src/components/Consequences/Cell/index.tsx
- packages/ui/src/pages/EntityPage/EntityVariantSummary/index.module.scss
- packages/ui/src/pages/EntityPage/EntityVariantSummary/index.tsx
[SKFP-900](https://d3b.atlassian.net/browse/SKFP-900)
- impact badge multiple size
- no color override for KF exception
- style fixes
> fix(variant): SKFP-900 summary variant fixes

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/pages/EntityPage/EntityVariantSummary/index.module.scss
- packages/ui/src/pages/EntityPage/EntityVariantSummary/index.tsx
[SKFP-900](https://d3b.atlassian.net/browse/SKFP-900)
> fix(variant): SKFP-900 summary variant

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/Widgets/AuthorizedStudies/AuthorizedStudiesListItem.tsx
- closes #[924](https://d3b.atlassian.net/browse/SKFP-924)
La description du ticket semble mentionner afficher Study Name (Study Code), mais je ne vois pas le Study Code.
> fix(authorizedstudies): SKFP-924 fix title and tooltip

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/pages/EntityPage/EntityConditionsCell/InheritanceTag.tsx
- closes [#SKFP-904](https://d3b.atlassian.net/browse/SKFP-904)
> fix: SKFP-904 adjusts casing on inheritance tag tooltip

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/pages/EntityPage/EntityVariantSummary/index.module.scss
- packages/ui/src/pages/EntityPage/EntityVariantSummary/index.tsx
- storybook/package-lock.json
[SKFP-900](https://d3b.atlassian.net/browse/SKFP-900)
- Adjust color on banner label and in details part label and value
> fix(entity): SKFP-900 fix variant summary style

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/pages/EntityPage/EntityDataset/index.module.scss
[SJIP-712](https://d3b.atlassian.net/browse/SJIP-712)
- increase space between stats
> fix(dataset): SJIP-712 style fixes

- packages/ui/Release.md
- packages/ui/jest.config.ts
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/layout/ResizableGridLayout/ResizableGridCard/index.tsx
- packages/ui/src/layout/ResizableGridLayout/index.tsx
- packages/ui/src/layout/ResizableGridLayout/utils.ts
- packages/ui/src/pages/EntityPage/EntityStatistics/index.module.scss
- packages/ui/src/pages/EntityPage/EntityStatistics/index.test.tsx
- packages/ui/src/pages/EntityPage/EntityStatistics/index.tsx
- packages/ui/src/pages/EntityPage/index.tsx
- packages/ui/src/utils/stringUtils.ts
- storybook/stories/Pages/EntityPage/EntityStatitistic.stories.tsx
- closes #[711](https://d3b.atlassian.net/browse/SJIP-711)
Add the Summary Statistics section to give a quick overview of the available data provided by a study. Note that we will not allow the Drag, resize, Addition or remove through chart selection tool in this page contrary to the summary view in the data exploration page.
https://www.notion.so/ferlab/Study-Entity-Page-ca49972b492e4389a9712f1927cc1a4d?pvs=4#df8983de174c43c79867425ea9a3a786
[[JIRA LINK]](https://d3b.atlassian.net/browse/SJIP-711)
...
@luclemo
> feat(entity): SJIP-711 add entity statistic

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/pages/EntityPage/EntityStatistics/index.module.scss
- closes #[TICKET_NUMBER](https://d3b.atlassian.net/browse/SJIP-711)
Il manque la margin bottom de 40px et la margin 16px du title
[JIRA LINK]
> fix(statistic): SJIP-711 Fix Entity Statistic style

- packages/ui/README.md
- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/pages/EntityPage/EntityConditionsCell/InheritanceTag.tsx
- packages/ui/src/pages/EntityPage/EntityTable/index.module.scss
- storybook/package-lock.json
All Entity Tables should be not striped
https://ferlab-crsj.atlassian.net/browse/CQDG-662
> feat: CQDG-662 force Entity Table not striped

- packages/ui/Release.md
- packages/ui/package.json
- packages/ui/src/pages/EntityPage/EntityStatistics/index.tsx
- closes #[711](https://d3b.atlassian.net/browse/SJIP-711)
https://d3b.atlassian.net/browse/SJIP-711
> fix(statistic): SJIP-711 fix graph X axis format

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/ProTable/Header/index.module.scss
- packages/ui/src/components/ProTable/Header/index.tsx
- packages/ui/src/components/ProTable/index.tsx
- packages/ui/src/components/ProTable/types.ts
[SJIP-764](https://d3b.atlassian.net/browse/SJIP-764)
- Add clear filters link option to pro table header component if filters selected
-
> feat(protable): SJIP-764 add clear filters

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/pages/EntityPage/EntityTitleLogo/index.module.scss
- packages/ui/src/pages/EntityPage/EntityTitleLogo/index.test.tsx
- packages/ui/src/pages/EntityPage/EntityTitleLogo/index.tsx
- packages/ui/src/pages/EntityPage/index.tsx
- storybook/package-lock.json
- storybook/stories/Pages/EntityPage/EntityTitleLogo.stories.tsx
[SJIP-774](https://d3b.atlassian.net/browse/SJIP-774)
- Add EntityTitleLogo
> feat(entity): SJIP-774 add EntityTitleLogo

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/pages/EntityPage/EntityConditionsCell/InheritanceTag.tsx
https://ferlab-crsj.atlassian.net/browse/CQDG-663
commentaire 3
> feat: CQDG-662 add Mitochondrial inheritance tag

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/pages/EntityPage/EntityConditionsCell/InheritanceTag.tsx
> feat: CQDG-662 add Mitochondrial inheritance tag 

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/pages/EntityPage/EntityStatistics/index.tsx
- closes #[791](https://d3b.atlassian.net/browse/SJIP-791)
Display no data when no Diagnoses MONDO like it is done for Most Frequent Phenotypes
[[JIRA LINK]](https://d3b.atlassian.net/browse/SJIP-791)
> feat(entity): SJIP-791 Fix phenotypes and mondo graph to display empty data

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/StatisticIcon/index.module.scss
[SJIP-797](https://d3b.atlassian.net/browse/SJIP-797)
- statistic icon style
> fix(statistic): SJIP-797 icon alignement

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/pages/EntityPage/EntityVariantSummary/index.tsx
[FLUI-129](https://ferlab-crsj.atlassian.net/browse/FLUI-129)
- align functionnal scores
[FLUI-129]: https://ferlab-crsj.atlassian.net/browse/FLUI-129?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(entity): FLUI-129 align scores

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/pages/LandingPage/BannerItem/index.module.scss
- packages/ui/src/pages/LandingPage/BannerItem/index.tsx
- packages/ui/src/pages/LandingPage/CavaticaCard/index.module.scss
- packages/ui/src/pages/LandingPage/CavaticaCard/index.tsx
- packages/ui/src/pages/LandingPage/Footer/index.module.scss
- packages/ui/src/pages/LandingPage/Footer/index.tsx
- packages/ui/src/pages/LandingPage/Studies/Carousel/index.tsx
- packages/ui/src/pages/LandingPage/Studies/Summary/index.tsx
- packages/ui/src/pages/LandingPage/Studies/index.tsx
- packages/ui/src/pages/LandingPage/TextIcon/index.module.scss
- packages/ui/src/pages/LandingPage/TextIcon/index.tsx
- packages/ui/src/pages/LandingPage/VariantCard/index.module.scss
- packages/ui/src/pages/LandingPage/VariantCard/index.tsx
- packages/ui/themes/default/_theme.template.scss
- storybook/stories/Pages/LandingPage/BannerItem.stories.tsx
- storybook/stories/Pages/LandingPage/TextIcon.stories.tsx
- storybook/stories/Pages/LandingPage/VariantCard.stories.tsx
- closes [#FLUI-130](https://ferlab-crsj.atlassian.net/browse/FLUI-130)
> fix: FLUI-130 Adjust some values for the landing page components

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/Widgets/Cavatica/CavaticaAnalyse.tsx
- packages/ui/src/components/Widgets/Cavatica/CavaticaAnalyzeModal.tsx
- packages/ui/src/components/Widgets/Cavatica/type.ts
- closes #[TICKET_NUMBER](https://d3b.atlassian.net/browse/SJIP-758)
[[JIRA LINK]](https://d3b.atlassian.net/browse/SJIP-758)
[Peek 2024-04-18 08-03.webm](https://github.com/Ferlab-Ste-Justine/ferlab-ui/assets/65532894/34e97742-9ccd-45f2-95a6-facb4c253398)
> fix(cavatica): SJIP-758 keep modal open

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/layout/ResizableGridLayout/ResizableGridCard/index.tsx
- packages/ui/src/layout/ResizableGridLayout/ResizableGridCard/utils.ts
- packages/ui/src/layout/ResizableGridLayout/index.tsx
- closes [#SJIP-818](https://d3b.atlassian.net/browse/SJIP-818)
> fix: SJIP-818 implement svg download for charts

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/Charts/Pie/index.tsx
[SJIP-811](https://d3b.atlassian.net/browse/SJIP-811)
> feat(piechart): SJIP-811 add class wrapper props

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/layout/ResizableGridLayout/ResizableGridCard/index.tsx
- packages/ui/src/layout/ResizableGridLayout/ResizableGridCard/utils.ts
- packages/ui/src/pages/EntityPage/EntityStatistics/index.tsx
- closes [#SJIP-803](https://d3b.atlassian.net/browse/SJIP-803)
> feat: SJIP-803 allow download of Entity Statistic charts

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/layout/ResizableGridLayout/ResizableGridCard/index.tsx
- packages/ui/src/layout/ResizableGridLayout/utils.ts
- packages/ui/src/pages/EntityPage/EntityStatistics/index.tsx
…previews
- closes [#SJIP-803](https://d3b.atlassian.net/browse/SJIP-803)
> fix: SJIP-803 fix the format of Entity Statistic charts download and previews

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/layout/ResizableGridLayout/index.tsx
- closes [#SJIP-831](https://d3b.atlassian.net/browse/SJIP-831)
> fix: SJIP-831 remove max rows on Resizable Grid Layout

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/Empty/index.tsx
[SKFP-971](https://d3b.atlassian.net/browse/SKFP-971)
- type ReactNode instead of string
> fix(empty): SKFP-971 update description type

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/SidebarMenu/index.module.scss
- packages/ui/src/components/SidebarMenu/index.tsx
- packages/ui/themes/default/_theme.template.scss
[SKFP-1041](https://d3b.atlassian.net/browse/SKFP-1041)
- improve style
- add props
- improve component
- Collapse
- Default
- Hover
- Focus
> feat(quickfilter): SKFP-1041 improve input

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/SidebarMenu/QuickFilter/index.tsx
- packages/ui/src/components/SidebarMenu/index.tsx
- closes [#SKFP-1043](https://d3b.atlassian.net/browse/SKFP-1043)
> feat: SKFP-1043 refactor quick filter component

- packages/ui/Release.md
- packages/ui/src/components/SidebarMenu/QuickFilter/index.module.scss
- packages/ui/src/components/SidebarMenu/QuickFilter/index.tsx
- packages/ui/src/components/SidebarMenu/index.tsx
- closes [#SKFP-1078](https://d3b.atlassian.net/browse/SKFP-1078)
> feat: SKFP-1078 add facet title selection

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/SidebarMenu/QuickFilter/index.tsx
- closes [#SKFP-1078](https://d3b.atlassian.net/browse/SKFP-1078)
> fix: SKFP-1078 prevent popover from closing when focusing input field

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/SidebarMenu/QuickFilter/index.tsx
- packages/ui/src/components/Widgets/AuthorizedStudies/FencesAuthentificationModal.tsx
[SKFP-1048](https://d3b.atlassian.net/browse/SKFP-1048)
> feat(quickfilter): SKFP-1048 add apply method

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/SidebarMenu/QuickFilter/index.tsx
[SKFP-1042](https://d3b.atlassian.net/browse/SKFP-1042)
> fix(quick filter): SKFP-1042 clean getSuggestion method

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/SidebarMenu/QuickFilter/index.module.scss
- packages/ui/themes/default/_theme.template.scss
[SKFP-1046](https://d3b.atlassian.net/browse/SKFP-1046)
- extract variable for background color
- remove space
> fix(quickfilter): SKFP-1046 update highlight style

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/SidebarMenu/index.tsx
- closes [#SKFP-1053](https://d3b.atlassian.net/browse/SKFP-1053)
> fix: SKFP-1053 remove visual glitch on side menu collapse

- packages/ui/Release.md
- packages/ui/package.json
- packages/ui/src/components/Consequences/Cell/index.tsx
- packages/ui/src/components/Consequences/utils.ts
- closes [#SKFP-1104](https://d3b.atlassian.net/browse/SKFP-1104)
> fix: SKFP-1104 temporarily change variant value renders

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/SidebarMenu/QuickFilter/index.module.scss
- packages/ui/src/components/SidebarMenu/QuickFilter/index.tsx
[SKFP-1106](https://d3b.atlassian.net/browse/SKFP-1106)
[SKFP-1107](https://d3b.atlassian.net/browse/SKFP-1107)
- clear instead of cancel button
- total results
> fix(quick filter): SKFP-1106 QF total result SKFP-1106 clear button

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/SidebarMenu/QuickFilter/index.tsx
> fix(quick filter): SKFP-1111 check same value

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/QueryBuilder/Header/Tools/QueryBuilderHeaderTools.module.scss
- packages/ui/themes/default/_mixins.scss
- closes https://ferlab-crsj.atlassian.net/browse/CLIN-2635
Set mixins for focus and focus-visible states in QueryBuilder Header, to make it easier to override.
> Fix CLIN-2635

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/SidebarMenu/QuickFilter/index.module.scss
- packages/ui/src/components/SidebarMenu/QuickFilter/index.tsx
- packages/ui/src/components/SidebarMenu/index.tsx
- packages/ui/src/components/filters/CheckboxFilter/CheckboxFilter.tsx
- packages/ui/src/components/filters/FilterSelector.tsx
- packages/ui/src/components/filters/RangeFilter.tsx
- packages/ui/src/components/filters/ToggleFilter.tsx
- packages/ui/src/components/filters/types.ts
- packages/ui/src/graphql/types.ts
[SKFP-1101](https://d3b.atlassian.net/browse/SKFP-1101)
- Manage boolean and range in facet view
- Add see more/less button for checkbox facet
- Checked existing facet values from active query
- Merge value from facet value and override from facet view
- Improve suggestion like facet from sidebar
> feat(Quick Filter): SKFP-1101 add boolean and range

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/SidebarMenu/QuickFilter/index.tsx
[SJFP-1149](https://d3b.atlassian.net/browse/SKFP-1149)
- reduce btn size
- Level 1
- Level 2
> fix(quick filter): SKFP-1149 apply btn style

- packages/ui/Release.md
- packages/ui/package.json
- packages/ui/src/components/Widgets/BiospecimenRequests/EditBiospecimenRequestModal.module.scss
- packages/ui/src/components/Widgets/BiospecimenRequests/EditBiospecimenRequestModal.test.tsx
- packages/ui/src/components/Widgets/BiospecimenRequests/EditBiospecimenRequestModal.tsx
- packages/ui/src/components/Widgets/BiospecimenRequests/index.test.tsx
- packages/ui/src/components/Widgets/BiospecimenRequests/index.tsx
- packages/ui/src/components/Widgets/BiospecimenRequests/utils.test.tsx
- packages/ui/src/components/Widgets/BiospecimenRequests/utils.tsx
- packages/ui/src/components/Widgets/widget.module.scss
- packages/ui/src/view/v2/GridCard/GridCardErrorPlaceholder.module.scss
- packages/ui/src/view/v2/GridCard/GridCardErrorPlaceholder.tsx
- storybook/stories/Components/BiospecimenRequests/BiospecimentRequests.stories.tsx
- closes #[1126](https://d3b.atlassian.net/browse/SKFP-1126)
[[JIRA LINK]](https://d3b.atlassian.net/browse/SKFP-1126)
> feat(dashboard): SKFP-1126 add biospecimen requests widgets

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/filters/CheckboxFilter/CheckboxFilter.tsx
- storybook/package-lock.json
[SKFP-1119](https://d3b.atlassian.net/browse/SKFP-1119)
- Au click sur “X More”, le bouton “Less” et ensuite le bouton “X More” perd son style.
> fix(facet): SKFP-1119 unfocus see more/less

- packages/ui/Release.md
- packages/ui/package.json
- packages/ui/src/components/Widgets/BiospecimenRequests/index.tsx
- closes #[1029](https://d3b.atlassian.net/browse/SKFP-1029)
> fix(biospecimen): SKFP-1029 fix handle share

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/QueryBuilder/Header/Tools/QueryBuilderHeaderTools.module.scss
- packages/ui/src/components/QueryBuilder/Header/Tools/index.tsx
- move dirty class to global space
https://ferlab-crsj.atlassian.net/browse/CLIN-2677
> fix: clin-2677

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/ProTable/Header/ItemsCount/index.tsx
- storybook/stories/Components/Tables/ProTable/ProTable.stories.tsx
- fix 'results' label when there is only 1 result
https://ferlab-crsj.atlassian.net/browse/CLIN-2635
> fix: clin-2635 fix 'results' label when there is only 1 result

- packages/ui/Release.md
- packages/ui/package.json
- packages/ui/src/components/OntologyTreeFilter/OntologyTree.test.tsx
- packages/ui/src/components/OntologyTreeFilter/OntologyTree.tsx
- packages/ui/src/components/OntologyTreeFilter/index.tsx
- packages/ui/src/components/OntologyTreeFilter/type.ts
- packages/ui/src/components/OntologyTreeFilter/utils.test.tsx
- packages/ui/src/components/OntologyTreeFilter/utils.tsx
- packages/ui/src/components/QueryBuilder/QueryPills/FieldQueryPill.tsx
- packages/ui/src/data/sqon/utils.ts
- closes #[822](https://d3b.atlassian.net/browse/SJIP-822)
Supprimer un item de l’ontology browser ne réaffiche pas tous les items du départ.
https://github.com/Ferlab-Ste-Justine/ferlab-ui/assets/65532894/9ac16eab-5472-43cf-9a7a-f85a4a063e92
[[822](https://d3b.atlassian.net/browse/SJIP-822)
> fix(ontologytree): SJIP-822 fix multiples issues

- packages/ui/src/components/QueryBuilder/QueryBar.module.css
- packages/ui/src/components/SidebarMenu/index.module.css
#Fix FLUI-132 padding-left for QueryBar
> feat: FLUI-132 fix padding-left for QueryBar

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/Widgets/Cavatica/index.tsx
- packages/ui/src/components/Widgets/widget.module.scss
- closes #[1010](https://d3b.atlassian.net/browse/SKFP-1010)
> fix(widget): SKFP-1010 fix error state style

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/view/v2/GridCard/GridCardHeader/GridCardHeader.module.scss
- packages/ui/src/view/v2/GridCard/GridCardHeader/index.tsx
- closes [#SKFP-1152](https://d3b.atlassian.net/browse/SKFP-1152)
> fix: SKFP-1152 change color and style in GridCardheader

- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/QueryBuilder/Header/Tools/QueryBuilderHeaderTools.module.css
- packages/ui/src/components/QueryBuilder/Header/index.module.css
- packages/ui/themes/default/theme.template.css
Do not review or merge this PR
> Feat/fl UI 132 fixs

- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/themes/bin/less2css.js
- closes #flui-136
[[JIRA LINK]](https://ferlab-crsj.atlassian.net/browse/FLUI-136)
> feat: FLUI-132 add script to simplify colors generation

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/FilterBox/Sorter.module.css
- packages/ui/src/components/FilterBox/Sorter.test.tsx
- packages/ui/src/components/FilterBox/Sorter.tsx
- packages/ui/src/components/FilterBox/index.module.css
- packages/ui/src/components/FilterBox/index.test.tsx
- packages/ui/src/components/FilterBox/index.tsx
- packages/ui/src/pages/CommunityPage/index.module.css
- packages/ui/src/pages/CommunityPage/index.test.tsx
- packages/ui/src/pages/CommunityPage/index.tsx
- packages/ui/src/pages/CommunityPage/type.ts
- packages/ui/src/utils/stringUtils.ts
- closes #[907](https://d3b.atlassian.net/browse/SKFP-907)
Normaliser la page member pour afin qu'elle puisse être utiliser sur plusieurs de nos platforms.
[[JIRA LINK]](https://d3b.atlassian.net/browse/SKFP-907)
> feat(community): SKFP-334 add community page

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/FilterBox/index.tsx
- packages/ui/src/pages/CommunityPage/CommunityAvatarHeader.test.tsx
- packages/ui/src/pages/CommunityPage/CommunityAvatarHeader.tsx
- packages/ui/src/pages/CommunityPage/CommunityBanner.test.tsx
- packages/ui/src/pages/CommunityPage/CommunityBanner.tsx
- packages/ui/src/pages/CommunityPage/CommunityMemberProfile.test.tsx
- packages/ui/src/pages/CommunityPage/CommunityMemberProfile.tsx
- packages/ui/src/pages/CommunityPage/CommunityMemberProfilePage.module.css
- packages/ui/src/pages/CommunityPage/CommunityMemberProfilePage.test.tsx
- packages/ui/src/pages/CommunityPage/CommunityMemberProfilePage.tsx
- packages/ui/src/pages/CommunityPage/CommunityUserAvatar.test.tsx
- packages/ui/src/pages/CommunityPage/CommunityUserAvatar.tsx
- packages/ui/src/pages/CommunityPage/index.tsx
- packages/ui/src/pages/CommunityPage/type.ts
- packages/ui/src/utils/stringUtils.ts
- storybook/stories/Pages/CommunityPage/CommunityMemberProfile.stories.tsx
- storybook/stories/Pages/CommunityPage/CommunityMembers.stories.tsx
- closes #[374](https://d3b.atlassian.net/browse/SKFP-374)
Portage de la page profile dans ferlab
[[JIRA LINK]](https://d3b.atlassian.net/browse/SKFP-374)
> feat(community): SKFP-334 add community member profile page

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/CustomPill/QueriesSidebar/QueryPill.tsx
- storybook/stories/Components/CustomPill/CustomPill.stories.tsx
https://ferlab-crsj.atlassian.net/browse/CLIN-2288
> feat: CLIN-2288 display queryPill name in bold

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/pages/CommunityPage/CommunityProfileGridCard.tsx
- closes #[TICKET_NUMBER](https://d3b.atlassian.net/browse/SKFP-374)
Add a template for profile grid card to display save and discard
[[JIRA LINK]](https://d3b.atlassian.net/browse/SKFP-374)
> feat(community): SKFP-374 add profile grid card

- packages/ui/src/pages/CommunityPage/CommunityMemberProfile.test.tsx
> test(community): SKFP-374 fix tests

- packages/ui/Release.md
- packages/ui/package.json
- packages/ui/src/components/FilterBox/index.tsx
- packages/ui/src/components/Gravatar/index.tsx
- packages/ui/src/pages/CommunityPage/CommunityAvatarHeader.tsx
- packages/ui/src/pages/CommunityPage/CommunityMemberProfilePage.module.css
- packages/ui/src/pages/CommunityPage/type.ts
- packages/ui/src/utils/stringUtils.ts
- packages/ui/themes/default/theme.template.css
- closes[ #TICKET_NUMBER](https://d3b.atlassian.net/browse/SKFP-906)
- closes[ #TICKET_NUMBER](https://d3b.atlassian.net/browse/SKFP-907)
1. La location ne s’affiche pas dans la « View Page Profile » 
2. Le bouton Community n’est pas de la bonne couleur dans la « View Page Profile »
3. Tous les utilisateurs ont la même image. C’est louche.
4. Ne pas afficher le rôle « other »
> fix(community): SKFP-334 fix styles

- .github/CODEOWNERS
- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/utils/sentry/localStorageIntegration.ts
- closes https://ferlab-crsj.atlassian.net/browse/FLUI-138
[[JIRA LINK]](https://ferlab-crsj.atlassian.net/browse/FLUI-138)
> feat: FLUI-138 add sentry local storage integration

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/Search/FLAutoComplete.tsx
- packages/ui/src/components/Search/fl-auto-complete.module.css
- storybook/stories/Components/QueryBuilder/QueryBuilder.stories.tsx
- storybook/stories/Components/Search/FLAutocomplete.stories.tsx
> feat: CLIN-3027 add an autocomplete component

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/Search/FLAutoComplete.tsx
- packages/ui/src/components/Search/fl-auto-complete.module.css
- packages/ui/themes/default/theme.template.css
> feat: CLIN-3027 update autocomplete highlight style

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/SidebarMenu/QuickFilter/index.tsx
- closes #[1136](https://d3b.atlassian.net/browse/SKFP-1136)
Need forceClose and handleClear to allow remote component
[[JIRA LINK]](https://d3b.atlassian.net/browse/SKFP-1136)
https://github.com/user-attachments/assets/db9b46b8-f154-4e68-9ccc-bab3f04a0537
> feat(quickfilter): SKFP-1136 add forceClose and handleClear

- packages/ui/.tscprc
- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/Search/FLAutoComplete.tsx
- packages/ui/src/components/Search/fl-auto-complete.module.css
- packages/ui/themes/default/theme.template.css
- storybook/stories/Components/Search/FLAutocomplete.stories.tsx
+ fix start script to allow css module files watch
https://ferlab-crsj.atlassian.net/browse/CLIN-3098
> feat: CLIN-3098 Update autocomplete component according to UI design

- packages/ui/Release.md
- packages/ui/package.json
- packages/ui/src/components/Search/FLAutoComplete.tsx
- storybook/stories/Components/Search/FLAutocomplete.stories.tsx
+ manage enter press
+ add a minimum length props for search term
+  add defaultValue and onClear props
+  select all text on focus
https://ferlab-crsj.atlassian.net/browse/CLIN-3098
> feat: CLIN-3098 Update autocomplete component

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/SidebarMenu/QuickFilter/index.module.css
- packages/ui/themes/default/theme.template.css
- closes #[TICKET_NUMBER](https://d3b.atlassian.net/browse/SJIP-952)
[[JIRA LINK]
](https://d3b.atlassian.net/browse/SJIP-952)
> fix(quickfilter): SJIP-952 allow quick filter facet color theme

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/filters/CheckboxFilter/CheckboxFilter.tsx
- closes CLIN-3047
[JIRA LINK](https://ferlab-crsj.atlassian.net/browse/CLIN-3047)
...
> fix: CLIN-3047 facet filter to use initial filters if filtered one is empty

- packages/ui/package-lock.json
> feat: CLIN-2983 package lock

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
> feat: CLIN-2983 version problem

- packages/ui/Release.md
- packages/ui/package.json
- packages/ui/themes/bin/less2css.js
feat: CLIN-3172 update less2css script to add 3rd parameter
> feat: CLIN-3172 update less2css script to add 3rd parameter

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/filters/CheckboxFilter/CheckboxFilter.tsx
- packages/ui/src/utils/stringUtils.test.ts
- packages/ui/src/utils/stringUtils.ts
- closes CLIN-3047
[JIRA LINK](https://ferlab-crsj.atlassian.net/browse/CLIN-3047)
...
> fix: CLIN-3047 checkbox filter with new accent remover function

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/BasicDescription/index.module.css
- packages/ui/src/components/BasicDescription/index.tsx
- closes #[TICKET_NUMBER](https://d3b.atlassian.net/browse/SJIP-958)
[[JIRA LINK]](https://d3b.atlassian.net/browse/SJIP-958)
> feat(description): add bordered basic description

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/Flag/FlagDropdown/index.tsx
- packages/ui/src/utils/dateUtils.test.ts
- packages/ui/src/utils/dateUtils.ts
- closes #CLIN-3217 et CLIN-3218
- Heure tronqué en anglais (CLIN-3217)
- Mauvais format d'heure en francais(CLIN-3218)
[JIRA LINK](https://ferlab-crsj.atlassian.net/browse/CLIN-3217)
[JIRA LINK](https://ferlab-crsj.atlassian.net/browse/CLIN-3218)
> fix: CLIN-3217 fix dateUtilis

- packages/ui/src/components/Charts/Readme.md
Add chart documentation for further dev
> chore(chart): FLUI-000 add chart readme for inter documentation

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/Flag/FlagDropdown/index.module.css
- packages/ui/src/components/Flag/FlagDropdown/index.tsx
- closes #CLIN-3216 et CLIN-3219
- Fix couleur highligh et text dropdown menu (CLIN-3216)
- Fix style bouton view history (CLIN-3219)
[JIRA LINK CLIN-3216](https://ferlab-crsj.atlassian.net/browse/CLIN-3216)
[JIRA LINK CLIN-3219](https://ferlab-crsj.atlassian.net/browse/CLIN-3219)
...
> fix: CLIN-3216 fix flag style

- packages/ui/Release.md
- packages/ui/package.json
- packages/ui/src/components/SidebarMenu/QuickFilter/index.module.css
- packages/ui/themes/default/theme.template.css
https://ferlab-crsj.atlassian.net/browse/CQDG-849
> feat: CQDG-849 add sidebar-quick-filter-highlight-text

- packages/eslint-config/index.js
- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/data/sqon/utils.ts
https://ferlab-crsj.atlassian.net/browse/CLIN-2673
> fix: CLIN-2673 Allow SelectRange filtering on 0 value

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/QueryBuilder/utils/helper.ts
- closes #CLIN-3284
[JIRA LINK](https://ferlab-crsj.atlassian.net/browse/CLIN-3284)
...
> fix: CLIN-3284 fix erreur 500

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/filters/CheckboxFilter/CheckboxFilter.tsx
[SKFP-1274](https://d3b.atlassian.net/browse/SKFP-1274)
- The search box is responsive to delete keystrokes.
https://github.com/user-attachments/assets/5ceee95e-72c0-494c-9ced-e9d7906482dc
https://github.com/user-attachments/assets/8834e326-e1a3-433a-95b2-c9fec46bea71
> fix(facet): SKFP-1274 search in checkbox filter

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/SidebarMenu/QuickFilter/index.module.css
- packages/ui/src/components/SidebarMenu/QuickFilter/index.tsx
- packages/ui/src/components/filters/CheckboxFilter/CheckboxFilter.module.css
- packages/ui/src/components/filters/CheckboxFilter/CheckboxFilter.tsx
- packages/ui/src/components/filters/types.ts
- packages/ui/src/data/filters/utils.ts
- Closes SJIP-281
- [JIRA](https://ferlab-crsj.atlassian.net/browse/SJIP-281)
1. 
2.
> feat(facet QF): SJIP-281 add category icon

- .github/workflows/create_pr_template.yml
> feat: FLUI-142 update pr template dynamicaly

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/UploadIds/UploadModal/index.tsx
- packages/ui/src/components/UploadIds/index.tsx
- Closes SJIP-1090
- [JIRA](https://d3b.atlassian.net/browse/SJIP-1090)
> feat(upload): SJIP-1090 add text transform mode

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/pages/LandingPage/Studies/Summary/index.module.css
- packages/ui/src/pages/LandingPage/Studies/Summary/index.tsx
- packages/ui/src/pages/LandingPage/Studies/index.tsx
- storybook/package-lock.json
- storybook/stories/Pages/LandingPage/Studies/Studies.stories.tsx
[SJIP-1103](https://ferlab-crsj.atlassian.net/browse/SJIP-1103)
Add view all studies button.
- Add a butotn in Studies section of landing page
Storybook
> feat(landing): SJIP-1103 add view all studies btn

- packages/ui/src/components/Charts/Venn/VennSkeleton.module.css
- packages/ui/src/components/Charts/Venn/index.tsx
- storybook/stories/Components/Chart/venn.stories.tsx
- Closes FLUI-145
Add total count of selected set
Add Venn Diagram with 2 sets
- [JIRA](https://ferlab-crsj.atlassian.net/browse/FLUI-145)
> feat(chart): FLUI-145 add total row, add dual venn mode

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/Charts/Venn/index.module.css
- packages/ui/themes/default/theme.template.css
- storybook/package-lock.json
- Closes FLUI-145
- [JIRA](https://ferlab-crsj.atlassian.net/browse/FLUI-145)
> fix(venn): FLUI-145 new color between hover and active state

- packages/ui/Release.md
- packages/ui/package.json
- packages/ui/src/components/Flag/FlagDropdown/index.module.css
- packages/ui/src/components/Flag/FlagDropdown/index.tsx
- Closes CLIN-3751
- [JIRA](https://ferlab-crsj.atlassian.net/browse/CLIN-3751)
1. 
2.
> fix: CLIN-3751 fix style icon flag

- packages/ui/Release.md
- packages/ui/package.json
- packages/ui/src/components/Assignments/AssignmentsSelect/index.tsx
- Closes PRESC-341
- [JIRA](https://ferlab-crsj.atlassian.net/browse/PRESC-341)
1. 
2.
> feat: PRESC-341 fix show ldm

- packages/ui/Release.md
- packages/ui/package.json
- packages/ui/src/components/Assignments/AssignmentsSelect/index.tsx
- Closes PRESC-341
- [JIRA](https://ferlab-crsj.atlassian.net/browse/PRESC-341)
1. 
2.
> feat: PRESC-341 add option to remove user assigment

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/ProTable/Pagination/index.tsx
- storybook/package-lock.json
- Closes CLIN-2484
- [JIRA](https://ferlab-crsj.atlassian.net/browse/CLIN-2484)
1. 
2.
> fix: CLIN-2484 Remove title attribute from ProTable pagination

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/pages/CommunityPage/type.ts
[SKFP-1429](https://ferlab-crsj.atlassian.net/browse/SKFP-1429)
Add somatic exploration page with query builder
- be able to save user config for new somatic page
> feat(user): SKFP-1429 add somatic to user config

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/QueryBuilder/index.module.css
- packages/ui/src/components/QueryBuilder/index.tsx
- Closes CLIN-3887
- [JIRA](https://ferlab-crsj.atlassian.net/browse/CLIN-3887)
1. 
2.
> feat: CLIN-3887 add scroll option querybuilder

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/pages/EntityPage/EntityVariantSummary/index.module.css
[SKFP-1432](https://ferlab-crsj.atlassian.net/browse/SKFP-1432)
rework style to be able to display multiple data on a line
https://github.com/user-attachments/assets/fa682e27-9a3d-4323-b46d-479862473789
> style(variant): SKFP-1432 entity variant summary

- packages/ui/Release.md
- packages/ui/package.json
- packages/ui/src/components/Charts/Venn/index.tsx
- storybook/stories/Components/Chart/venn.stories.tsx
Add invisible set, manage sets with more than 10 000 results
- [JIRA](https://ferlab-crsj.atlassian.net/browse/SJIP-1116)
> feat(venn): SJIP-1116 add invisible set

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/Charts/Venn/VennModal.tsx
- packages/ui/src/components/Charts/Venn/index.module.css
- packages/ui/src/components/Charts/Venn/index.tsx
- storybook/stories/Components/Chart/venn.stories.tsx
- [JIRA](https://ferlab-crsj.atlassian.net/browse/SJIP-1116)
> fix(venn): SJIP-1116 add analytics, fix typo and styles

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/Charts/Venn/index.tsx
- [JIRA](https://ferlab-crsj.atlassian.net/browse/SJIP-1116)
> fix(venn): SJIP-1116 format entity count

- packages/ui/src/components/Charts/Venn/index.tsx
Update inner doc for futur devs
> doc(venn): SJIP-1116 update inner doc

- .github/workflows/quality.yml
- .github/workflows/uilinter.yml
- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/ProTable/ColumnSelector/index.module.css
- Closes CLIN-3908
- [JIRA](https://ferlab-crsj.atlassian.net/browse/CLIN-3908)
1. 
2.
> feat: CLIN-3908 add scrollbar gutter

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/pages/EntityPage/EntityStatistics/index.tsx
- Closes UNIC-36
- [JIRA](https://ferlab-crsj.atlassian.net/browse/UNIC-36)
1. 
2.
> feat: UNIC-36 fix vulne on cross-spawn 7 0 3 and fix bad import on EntityStatistics

- packages/ui/Release.md
- packages/ui/package.json
- packages/ui/src/components/Charts/Venn/index.module.css
- Closes SKFP-1399
- [JIRA](https://ferlab-crsj.atlassian.net/browse/SKFP-1399)
> fix(venn): SKFP-1399 fix select box width

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/Charts/Venn/index.module.css
- packages/ui/src/components/QueryBuilder/QueryTools.module.css
- packages/ui/themes/default/theme.template.css
- Closes SJIP-1399
Adjust title
- [JIRA](https://ferlab-crsj.atlassian.net/browse/SJIP-1399)
> fix(venn): SJIP-1399 adjust title color

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/ProTable/SummarySumCell/index.module.css
- packages/ui/src/components/ProTable/SummarySumCell/index.tsx
- Closes SJIP-1190
- [JIRA](https://ferlab-crsj.atlassian.net/browse/SJIP-1190)
> fix(table): SJIP-1190 add SummarySumCell

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/Flag/FlagDropdown/index.module.css
- packages/ui/src/components/Flag/FlagDropdown/index.tsx
- Closes CLIN-4209
- [JIRA](https://ferlab-crsj.atlassian.net/browse/CLIN-4209)
1. 
2.
> feat: CLIN-4209 flag history button more visible

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/Flag/FlagDropdown/index.module.css
- packages/ui/src/components/Flag/FlagDropdown/index.tsx
- Closes CLIN-4209
- [JIRA](https://ferlab-crsj.atlassian.net/browse/CLIN-4209)
1. 
2.
> fix: CLIN-4209 use type link and popover to the right

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/Charts/Venn/VennChartWithFilters/index.tsx
- storybook/package-lock.json
[SJIP-1297](https://ferlab-crsj.atlassian.net/browse/SJIP-1297)
Open sets dropdown when entity is selected.
Open sets dropdown when entity is selected.
dropdown not open on change. 
https://github.com/user-attachments/assets/c1681d84-8d16-4cac-9fbe-fef401afd988
> fix(venn): SJIP-1297 manage dropdown open

- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/BiospecimenRequest/requestBiospecimen.utils.tsx
- storybook/package-lock.json
- [SKFP-1504](https://ferlab-crsj.atlassian.net/browse/SKFP-1504)
Add set type for somatic
Add set type for somatic
> feat(set): SKFP-1504 add set type

- packages/ui/Release.md
- Closes SKFP-1504
- [JIRA](https://ferlab-crsj.atlassian.net/browse/SKFP-1504)
1. 
2.
> feat(set): SKFP-1504 update release md file

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/Charts/ClinicalTrialTimeline/index.tsx
- storybook/package-lock.json
- storybook/stories/Components/Chart/timeline.stories.tsx
OC for a visual representation of a clinical trial study design. In order to explore how to display time-based clinical activities, visits, and interventions in an interactive and reusable way across studies. This will give a better idea to users of the protocol used for a given study in the study entity page and what data was generated from the steps in the protocol.
- [JIRA](https://ferlab-crsj.atlassian.net/browse/)
> feat(chart): add clinical trial timeline chart

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/Charts/Venn/SaveModal.tsx
- storybook/package-lock.json
[SKFP-1508](https://ferlab-crsj.atlassian.net/browse/SKFP-1508)
Update title save modal for somatic variant
- display variant title for somatic
Participant title
> fix(venn): SKFP-1508 update save modal title for somatic

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/Charts/Venn/VennChartWithFilters/index.tsx
- packages/ui/src/components/Charts/Venn/VennChartWithSelect.tsx
- packages/ui/src/components/Charts/Venn/VennModal.tsx
- packages/ui/src/components/Charts/Venn/index.module.css
- packages/ui/src/components/Charts/Venn/index.tsx
- storybook/package-lock.json
- storybook/stories/Components/Chart/vennWithFilters.stories.tsx
- storybook/stories/Components/Chart/vennWithSelect.stories.tsx
- Closes SJIP-1339
- [JIRA](https://ferlab-crsj.atlassian.net/browse/SJIP-1339)
> fix(venn): SJIP-1339 make venn responsive

- packages/ui/Release.md
- packages/ui/package.json
- packages/ui/src/components/Charts/ClinicalTrialTimeline/index.tsx
- storybook/package-lock.json
- storybook/stories/Components/Chart/timeline.stories.tsx
- Closes SJIP-1318
- [JIRA](https://ferlab-crsj.atlassian.net/browse/SJIP-1318)
> fix(chart): SJIP-1318 make timeline responsive

- packages/ui/Release.md
- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/List/ListItemWithActions.tsx
[SJIP-1354](https://ferlab-crsj.atlassian.net/browse/SJIP-1354)
Select one or more saved sets of the same entity types using checkboxes directly in the Saved Sets Dashboard.
- Add avatar props to ListItemWithAction to be able to add a checkbox by item
> feat(list): SJIP-1354 add avatar to list with action

- packages/ui/package.json
- packages/ui/src/pages/LandingPage/BannerItem/index.module.css
- packages/ui/src/pages/LandingPage/BannerItem/index.tsx
- storybook/stories/Pages/LandingPage/BannerItem.stories.tsx
- Closes SJIP-1420
- [JIRA](https://ferlab-crsj.atlassian.net/browse/SJIP-1420)
1. 
2.
> feat: SJIP-1420 Add option button to Landing page BannerItem

- packages/ui/package.json
- packages/ui/src/pages/LandingPage/Footer/index.module.css
- packages/ui/src/pages/LandingPage/Footer/index.tsx
- storybook/stories/Pages/LandingPage/Footer.stories.tsx
- [JIRA](https://ferlab-crsj.atlassian.net/browse/)
1. 
2.
> feat: flui-153 add policies to footer
