packages/ui/package.json
packages/ui/src/components/filters/CheckboxFilter.tsx

There is a bug on cqdg and kf, were when you change you selection in the querybar (updating the filters). The checkbox cannot represent the current status even if the proper value is sent to antd checkbox component
Before:
https://user-images.githubusercontent.com/98903/113296394-b2404300-92f9-11eb-8334-d8469d541976.mov
After:
https://user-images.githubusercontent.com/98903/113296423-bd936e80-92f9-11eb-8565-cb84bce8c408.mov

fix: checkbox does not check correctly on filter change(querybar)

---

packages/style/components/filters/ToggleFilter.module.scss
packages/style/package.json

Design update for all projects

fix toggle filters tag count to be displayed on the right

---

packages/ui/README.md
packages/ui/package.json
packages/ui/src/components/QueryBuilder/utils/useQueryBuilderState.tsx
packages/ui/src/data/sqon/utils.ts

- closes #[393](https://d3b.atlassian.net/browse/SKFP-393)
KF portal's `Age at diagnosis` graph needs to trigger a graphlql request with RangeOperator
[BONUS]
I updated the installation documentation
https://user-images.githubusercontent.com/65532894/197047097-fb0e7bdb-9922-4759-99bd-86da0f0adeb0.mp4

feat: SKFP-393 updateActiveQueryField now support RangeOperators

---

packages/ui/README.md
packages/ui/package.json
packages/ui/src/components/filters/FilterContainer.tsx
packages/ui/src/components/filters/types.ts
packages/ui/src/data/filters/Range.ts
packages/ui/src/data/filters/utils.ts
storybook/stories/Components/Filters/FilterContainer.stories.tsx

- closes #[283](https://d3b.atlassian.net/browse/SKFP-283)
Facets should be able to display a tooltips when needed
1. Tooltips can be defined when passing FilterInfo to ferlab-ui
```javascript
{
title: intl.get('facets.genePanels'),
facets: [
'genes__hpo__hpo_term_label',
'genes__orphanet__panel',
'genes__omim__name',
'genes__ddd__disease_name',
'genes__cosmic__tumour_types_germline',
],
tooltips: [
'genes__hpo__hpo_term_label',
'genes__omim__name',
'genes__ddd__disease_name',
'genes__cosmic__tumour_types_germline',
],
},
```
2. Add a facets dictionary in your project. If your don't want to use the display_name property, you can setup a custom tooltips text inside the tooltips section
```javascript
export const getFacetsDictionary = () => ({
genes: {
cosmic: { …
```

feat: SKFP-283 add tooltips to facet header

---

packages/style/components/collapse/Collapse.module.scss
packages/style/package.json
packages/ui/package.json
packages/ui/src/components/Collapse/index.tsx

- closes #3242
FLUI-8 adjust collaps header title size
https://ferlab-crsj.atlassian.net/browse/FLUI-8
header size 16px for default and large 

feat: FLUI-8 adjust collaps header title size

---

packages/ui/Release.md
packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/components/QueryBuilder/QueryPills/BooleanQueryPill.tsx
packages/ui/src/components/QueryBuilder/QueryPills/FieldQueryPill.tsx
packages/ui/src/components/QueryBuilder/QueryPills/IsolatedBooleanQueryPill.tsx
packages/ui/src/components/QueryBuilder/QueryValues.tsx
packages/ui/src/components/QueryBuilder/index.tsx
packages/ui/src/components/QueryBuilder/types.ts
packages/ui/src/components/filters/RangeFilter.tsx
packages/ui/src/components/filters/types.ts
packages/ui/src/data/filters/Range.ts
packages/ui/src/data/sqon/types.ts
packages/ui/src/data/sqon/utils.ts

- closes FLUI-4
Fix no data checkbox for rangerfilter that was breaking QueryBuilder
https://user-images.githubusercontent.com/28421005/199884077-e22fc155-febe-41b1-a3df-9a061961756a.mov
Image that shows that the operator for the Range Filter Values and Missing Value stays to `Or` even when the query bar operator is changed to `And`

Fl UI 4 olivier

---

packages/style/components/protable/Pagination.module.scss
packages/style/package.json
packages/ui/package.json
packages/ui/src/components/ProTable/Pagination/constants.ts
packages/ui/src/components/ProTable/Pagination/index.tsx
packages/ui/src/components/ProTable/Pagination/utils.ts
packages/ui/src/components/ProTable/index.tsx
packages/ui/src/components/ProTable/types.ts
packages/ui/src/components/ProTable/utils.ts
packages/ui/src/components/QueryBuilder/types.ts
packages/ui/src/graphql/constants.ts
packages/ui/src/graphql/types.ts
packages/ui/src/graphql/utils.ts
storybook/stories/Components/Tables/ProTable/ProTable.stories.tsx

- closes #[522](https://d3b.atlassian.net/browse/SKFP-522)
1. Ajout de la gestion du `SearchAfter`
2. Export des types communs côté ferlab-ui concernant graphql
À lire
[Guide de migration](https://www.notion.so/ferlab/Search-After-guide-de-migration-Front-End-8a0cd7ed40984f219f0174d64404b09b)
[Kids First PR](https://github.com/kids-first/kf-portal-ui/pull/3575)
À noter que l'ancienne pagination devrait toujours être compatible.

✨feat(variant): SKFP-522 add afterSearch, refact code

---

packages/ui/package.json
packages/ui/src/components/ProTable/Pagination/index.tsx
packages/ui/src/components/ProTable/index.tsx

- closes #[522](https://d3b.atlassian.net/browse/SKFP-522)
Notion updated : https://www.notion.so/ferlab/Search-After-guide-de-migration-Front-End-8a0cd7ed40984f219f0174d64404b09b
1. Désactiver le bouton Next quand il n’y a qu’une seule page d’affichée pour éviter d’afficher une page vide en cliquant sur Next.
2. Désactiver le bouton Next lorsqu’il n’y a aucun résultat. Note: Cliquer sur Next ne fait rien ici.
3. Retourner à la première page au changement de requête.
4. Il n’est pas possible d’afficher les résultats au delà de 10K éléments.
https://user-images.githubusercontent.com/65532894/202556063-99313a42-06f6-480a-8447-1ddbb47c4377.mp4
@kstonge

🐛fix(pagination): SKFP-522 fix next button disable behaviour

---

packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/components/QueryBuilder/index.tsx

- closes https://ferlab-crsj.atlassian.net/browse/CLIN-1526
Gestion des erreurs qui apparaissent lors de la création des requêtes de variants. 
Cette story est sensée répondre à cette problématique: 
Plantage lors d’une combinaison de requêtes :
QUI : une utilisatrice de CLIN fait des requêtes combinées tombe de temps en temps sur une erreur 500. Une fois au 3 jours ouvrables. Quand ça arrive il est impossible d’ouvrir la page variant.
[ ] Désactivé la checkbox de la query en cours.

fix: FLUI-18 no checkbox for active query

---

packages/ui/Release.md
packages/ui/package.json
packages/ui/src/layout/SortableGrid/index.tsx

https://ferlab-crsj.atlassian.net/browse/CQDG-110
```const [currentItems, setCurrentItems] = useState(items);```
this useState blocks `items` so the translations are never changed
useEffect is used to re-`setCurrentItems` when `items` props change

fix: CQDG-110 rerender when prop change

---

packages/style/components/queryBuilder/QueryBuilderHeaderTools.module.scss
packages/style/package.json
packages/ui/package.json
packages/ui/src/components/ProTable/index.tsx
packages/ui/src/components/ProTable/types.ts

- closes #[25](https://ferlab-crsj.atlassian.net/browse/FLUI-25)
- closes #[26](https://ferlab-crsj.atlassian.net/browse/FLUI-26)
QueryBuilderHEaderTools surcharge le hover des boutons et retire le background. Cependant, il devrait garder le fonctionnement des bases des boutons.
Ajouter une clé de traduction pour pouvoir redéfinier la props description de Empty lorsqu’aucun résultat n’est sortie
A noter qu'à cause de problème de builds, la capture d'écran de querytools a été prise via storybook
##

Feat/fl UI 25 26/fix table and query builder tools

---

packages/ui/package.json
packages/ui/src/components/ProTable/Pagination/index.tsx
packages/ui/src/components/ProTable/types.ts
packages/ui/src/pages/VariantEntity/Consequences/index.tsx

- closes #[575](https://d3b.atlassian.net/browse/SKFP-575)
- closes #[581](https://d3b.atlassian.net/browse/SKFP-581)
1. Vincent requested we adjust the default row view from 10/view to 20/view. Also save the user’s parameter to the latest row view setting. E.g. if the user select 100/view, closes his session, relogs in, the table of results should be maintained at 100/view and not reinitialized to 20/view (being the default).
2. Replace underscores with spaces for Interpretation and Consequences values in Variant Entity page.
https://user-images.githubusercontent.com/65532894/208143193-76beeb09-fc07-44ed-8775-f65b1794037d.mp4

Feat/skfp 575/view save

---

packages/ui/package.json
packages/ui/src/pages/EntityPage/EntityTable/index.tsx

- closes #403
Header props need to be an ReactNode for some cases.

✨fix(entity): SKFP-403 remove string only limitation

---

packages/ui/package.json
packages/ui/src/data/sqon/operators.ts
packages/ui/src/data/sqon/types.ts
packages/ui/src/data/sqon/utils.ts

#FEATURE 
- closes #3242
Goal: Modify the Search by study to the improved search on the server side.
E.g. Currently server side strategy: you need to input TARGET: Neuroblastoma  to have the resulting study show up. You cannot write Neuroblastoma as it does not respect the order of the words and characters of the Study Name. 
We would want the Search by study to be able to search for any string Study Name without respecting the specific order of the words and characters. Similar to what we see in prod currently. 
It is not necessary to identify a study by finding the letters within a word. E.g., imagine a value “hello”. We would want to be able to input he or He or HE  to find the value but it is not necessary to find the study by entering  “ello”.
Solution provided by Evans:
```json
{ …
```

✨feat(search): SKFP-603 add wild card search

---

packages/style/Release.md
packages/style/package.json
packages/style/pages/EntityPage/EntityTable.module.scss
packages/style/pages/EntityPage/EntityTitle.module.scss
packages/style/themes/default/_theme.template.scss
packages/ui/Release.md
packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/pages/EntityPage/EntityTitle/index.tsx

- closes [SJIP-350](https://d3b.atlassian.net/browse/SJIP-350)
- Ajustement de la taille par défaut de l'icône des pages entités
- Update du package simplebar-react pour fixer les anchorLink dans Include
- Cleanup de code inutilisé dans EntityTable.module.scss

fix: SJIP:350 Default icon size for entity pages

---

packages/ui/Release.md
packages/ui/package.json
packages/ui/src/components/ProTable/index.tsx
packages/ui/src/components/ProTable/types.ts
packages/ui/src/pages/EntityPage/EntityTable/index.tsx

- closes [SJIP-364](https://d3b.atlassian.net/browse/SJIP-364)
- Add a scroll when EntityTable has a height of at least 400px

fix: SJIP:364 Add scroll to EntityTable

---

packages/ui/Release.md
packages/ui/package.json
packages/ui/src/components/UploadIds/types.ts

- closes [SKFP-605](https://d3b.atlassian.net/browse/SKFP-605)
- Add a value property to MatchTableItem to handle use cases where all other properties are necessary but cannot be used as queried value. 
- Related to https://github.com/kids-first/kf-portal-ui/pull/3682

fix: SKFP-605 Case insensitive upload

---

packages/ui/package.json
packages/ui/src/pages/EntityPage/EntityTable/index.tsx

- closes #[45](https://ferlab-crsj.atlassian.net/browse/FLUI-45)
La client height ne se déclenchait pas car la référence était null dans useEffect. useCallback semble corriger le probleme.

fix(entitytable): FLUI-45 fix client height

---

packages/ui/package.json
packages/ui/src/components/ProTable/Header/ItemsCount/index.tsx
packages/ui/src/components/ProTable/Pagination/index.tsx
packages/ui/src/components/ProTable/index.tsx
packages/ui/src/components/ProTable/types.ts
packages/ui/src/components/ProTable/utils.ts

- closes #[29](https://ferlab-crsj.atlassian.net/browse/FLUI-29)
- closes #[39](https://ferlab-crsj.atlassian.net/browse/FLUI-39)
- closes #[42](https://ferlab-crsj.atlassian.net/browse/FLUI-42)
Un fix client doit aussi être appliqué afin de retirer le searchafter lorsqu'on modifie la query
```
useEffect(() => {
if (selectedKeys.length) {
setSelectedKeys([]);
setSelectedRows([]);
}
resetSearchAfterQueryConfig(
{
...DEFAULT_QUERY_CONFIG,
sort: DEFAULT_BIOSPECIMEN_QUERY_SORT,
size:
userInfo?.config?.data_exploration?.tables?.biospecimens?.viewPerQuery ||
DEFAULT_PAGE_SIZE,
},
setQueryConfig,
);
setPageIndex(DEFAULT_PAGE_INDEX);
// eslint-disable-next-line
}, [JSON.stringify(activeQuery)]);
```
https://user-images.githubusercontent.com/65532894/228635245-c32694ec-a7f7-458 …

fix(pagination): FLUI-29 FLUI-42 FLUI-39 fix searchafter

---

packages/ui/package.json
packages/ui/src/components/ProTable/Pagination/index.tsx

- closes #[59](https://ferlab-crsj.atlassian.net/browse/FLUI-59)
Filtrer le tableau pour avoir un nombre de résultat restraint (e.g. 11 résultat, viewPerQuery de 10)
Faire next
Next permet encore d'aller plus loin alors qu'il devrait être bloqué
https://user-images.githubusercontent.com/65532894/229149015-46853f4d-6605-497c-be1e-60a8f2358f4e.mp4
https://user-images.githubusercontent.com/65532894/229149110-f0337d64-e490-468b-8c29-99b8b787289c.mp4
@kstonge

fix(searchafter): FLUI-59 fix next button

---

package-lock.json
packages/ui/Release.md
packages/ui/package.json
packages/ui/src/components/UserAvatar/index.test.tsx
packages/ui/src/components/UserAvatar/index.tsx
storybook/stories/Components/UserAvatar/UserAvatar.stories.tsx

- closes #3242
Simple way to create users avatar based on their names, google like.
If `src` is defined then display proper image.
[![image](https://user-images.githubusercontent.com/15524246/233173046-f02170de-c544-4f6d-955a-695aa2015bea.png)](https://files.slack.com/files-pri/TFDLDE8J3-F054QV11ZCG/image.png)
[![image](https://user-images.githubusercontent.com/15524246/233173097-71e71724-a266-4c38-a7f2-0bfcc3dec007.png)](https://files.slack.com/files-pri/TFDLDE8J3-F0543Q2G85A/image.png)

feat: CQDG-215 create UserAvatar with auto color by users name

---

packages/ui/package.json
packages/ui/src/layout/ResizableGridLayout/ResizableItemSelector/index.module.scss
packages/ui/src/layout/ResizableGridLayout/ResizableItemSelector/index.tsx
packages/ui/src/layout/ResizableGridLayout/index.module.scss
packages/ui/src/layout/ResizableGridLayout/index.tsx
packages/ui/src/view/v2/GridCard/Gridcard.module.scss
packages/ui/themes/default/_colors.scss

- closes #[664](https://d3b.atlassian.net/browse/SKFP-664)
1. Le Click Target du resizer devrait être 16x16
2. L’icône du resizer devrait être 8x8
3. Griser le bouton Reset lorsqu’on est à l’état initial
https://user-images.githubusercontent.com/65532894/234357692-8c96e3c4-2964-4bf8-a1b0-55b3a33cf419.mp4
4. Renommer le tooltip de la personnalisation « Charts »
5. Limiter l’action du drag au header des cartes, les fonctionnalités des graphiques fonctionnent mal
https://user-images.githubusercontent.com/65532894/234357803-6915b8f8-7287-4ccf-a693-58e9315ab1bb.mp4
6. Modifier le curseur lors d’un hover sur toute la header des cartes (pas juste sur les 6 p’tits points)
https://user-images.githubusercontent.com/65532894/234357853-dd917387-c423-4e38-b872-daf03a460964.mp4

fix(resizablegrid): SKFP-664 fix drag handle and menu behavior

---

packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/data/arranger/formatting.ts

- closes #[389](https://d3b.atlassian.net/browse/SJIP-389)
Actuellement, on cast chaque valeur 0 ou 1 en boolean, ce qui cause des conflits au niveau des chromosomes. 
1 - Côté client,  Ajouter key_as_string dans la requêtre des aggregas `src/graphql/queries.ts`
```typescript
const generateAggregations = (extendedMappingFields: TExtendedMapping[]) => {
const aggs = extendedMappingFields.map((f) => {
if (['keyword', 'id'].includes(f.type)) {
return (
dotToUnderscore(f.field) +
' {\n     buckets {\n      key\n        key_as_string\n        doc_count\n    }\n  }'
);
} else if (['long', 'float', 'integer', 'date'].includes(f.type)) {
return dotToUnderscore(f.field) + '{\n    stats {\n  max\n   min\n    }\n    }';
} else if (['boolean'].includes(f.type)) {
return (
dotToUnderscore(f.field) +
' …
```

fix(filter): SJIP use key_as_string instead of key for boolean

---

packages/ui/package.json
packages/ui/src/components/ProTable/index.tsx

- closes #[413](https://d3b.atlassian.net/browse/SJIP-413)
Vue que loading a été déconstruit, il n'était plus envoyere à Protable

fix(protable): SJIP-413 fix loading props regression

---

packages/ui/src/components/Collapse/index.tsx
packages/ui/src/pages/EntityPage/EntityDescriptions/index.tsx
packages/ui/src/pages/EntityPage/EntityExpandableTableMultiple/index.tsx
packages/ui/src/pages/EntityPage/EntityTable/index.tsx
packages/ui/src/pages/EntityPage/EntityTableMultiple/index.tsx
packages/ui/src/pages/EntityPage/EntityTableRedirectLink/index.module.scss
packages/ui/src/pages/EntityPage/EntityTableRedirectLink/index.tsx
packages/ui/src/pages/EntityPage/index.tsx
packages/ui/themes/default/_theme.template.scss
storybook/stories/Pages/EntityPage/EntityExpandableTableMultiple.stories.tsx
storybook/stories/Pages/EntityPage/EntityTable.stories.tsx
storybook/stories/Pages/EntityPage/EntityTableMultiple.stories.tsx

- closes #[423](https://d3b.atlassian.net/browse/SJIP-423)
Similar to the Statistic buttons that are used to redirect to the Data Exploration, we will add a button “View in data exploration” on the right side of the table title for the respective entities. The filter to the Data Exploration page will be the same as the filters in the statistic button for the respective entity. 
Participant Entity tables:
Biospecimen (query = Participant ID, tab = Biospecimens)
Data File (query = Participant ID, tab = Data Files)
File Entity tables:
Participant / Sample  (query = File ID, tab = Participants)

feat(entity): SJIP-423 add table extra and redirect link

---

packages/ui/package.json
packages/ui/src/pages/EntityPage/EntityExpandableTableMultiple/index.tsx
packages/ui/src/pages/EntityPage/EntityTable/index.tsx
packages/ui/src/pages/EntityPage/EntityTableMultiple/index.tsx

- closes #[414](https://d3b.atlassian.net/browse/SJIP-414)
Goal:  Add number of total row items per table and place it beside the respective Table titles. 
This applies to the Diagnosis, Phenotype, Biospecimen Data File in Participant Entity page. 
This applies to the Participant / Sample table in the File Entity page
In the case of Data files table, since the files are not enumerated per row, take the total number of files associated with the Entity. 
For CQDG, There is an additional table that would need this feature, Files Generated by the Analysis, in the File Entity page which doesn’t appear in KF/INCLUDE.
Do not indicate the number “0” beside the table title if there is no data in the table.
E.g.  Diagnosis (5)
If the participant has 5 unique diagnoses (row level), then indicate in …

feat(entity): SJIP-414 add total in panel header

---

packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/components/Charts/Bar/index.module.scss
packages/ui/src/components/Charts/Bar/index.tsx
packages/ui/src/components/Charts/Pie/index.module.scss
packages/ui/src/components/Charts/Pie/index.tsx
packages/ui/src/layout/ResizableGridLayout/index.tsx
packages/ui/src/view/v2/GridCard/Gridcard.module.scss
packages/ui/themes/default/_theme.template.scss
storybook/stories/Components/Chart/bar.stories.tsx
storybook/stories/Components/Chart/pie.stories.tsx

- closes #[692](https://d3b.atlassian.net/browse/SKFP-692)
Afin d'unifier nos projets, les graphiques seront maintenant géré côté ferlab-ui.
Pour le moment, nivo reste en 0.80 (et non en 0.83 à cause de ce [ticket](https://github.com/plouc/nivo/issues/2310)). Sauf que la verison 0.83 contenait des fix pour les tests unitaires.

feat(chart): SKFP-692 add pie and chart graphics

---

packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/components/Charts/Bar/index.tsx
packages/ui/src/components/Charts/Pie/index.tsx
packages/ui/src/graphql/types.ts
packages/ui/src/layout/ResizableGridLayout/ResizableGridCard/index.module.scss
packages/ui/src/layout/ResizableGridLayout/ResizableGridCard/index.tsx
packages/ui/src/layout/ResizableGridLayout/ResizableItemSelector/index.tsx
packages/ui/src/layout/ResizableGridLayout/index.tsx
packages/ui/src/layout/ResizableGridLayout/utils.ts
packages/ui/src/utils/numberUtils.ts
packages/ui/src/view/v2/GridCard/GridCard.tsx
storybook/stories/Layout/ResizableGridLayout.stories.tsx

- closes #[698](https://d3b.atlassian.net/browse/SKFP-698)
```
Implement the download by png, svg through a preview modal that will include the chart values and legend. In the modal, the user will have a preview of the chart and will be able to confirm and proceed to the download for the specific file format (PNG, SVG), or cancel and close the modal. The download data will be done directly from the chart’s dropdown and will not open a modal. (TSV) . 
- Modal title: “Download preview – Chart Title"
Download PNG/SVG values and legend examples:
Demographics, Participant by Data Type, Participant by Data Category, Age at Diagnosis, Studies.
Value: Male , Count: 6769, Frequency: (50.89%) 
e.g.,red Male 6769 (50.89%)
- For the 2 sunbursts, for now we can display simply display the image of the …
```

feat(resizableGrid): SKFP-698 add download graph data

---

packages/ui/package.json
packages/ui/src/utils/localeUtils.test.ts
packages/ui/src/utils/localeUtils.ts
packages/ui/src/utils/numberUtils.test.ts
packages/ui/src/utils/numberUtils.ts

[FLUI-65](https://ferlab-crsj.atlassian.net/browse/FLUI-65)
Actually the method `numberFormat` takes by default the local of the browser when it’s not specified. We would like to choose and specify the locale to display the right format.
...

feat(number): FLUI-65 manage locale in number

---

packages/ui/package.json
packages/ui/src/components/Assignments/AssignmentsFilter/index.module.scss
packages/ui/src/components/Assignments/AssignmentsFilter/index.test.tsx
packages/ui/src/components/Assignments/AssignmentsFilter/index.tsx
packages/ui/src/components/Assignments/AssignmentsSelect/index.module.scss
packages/ui/src/components/Assignments/AssignmentsSelect/index.test.tsx
packages/ui/src/components/Assignments/AssignmentsSelect/index.tsx
storybook/stories/Components/Assignment/AssignmentSelect.stories.tsx

- closes #CLIN-1773
Ajout de l'option visibleOptions false dans le component de assignementSelect.
[JIRA LINK]
https://ferlab-crsj.atlassian.net/browse/CLIN-1773
Toujours ouvert
Fermé ou Ouvert
...

feat: CLIN-1773 assignment select visible false

---

packages/ui/Release.md
packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/components/filters/RangeFilter.tsx
packages/ui/src/components/filters/types.ts
storybook/stories/Components/Filters/RangeFilter.stories.tsx

- closes #CLIN-1991
Move RangeFilter noDataInputOption into config instead of props
[JIRA LINK]
Able to show/hide the noData checkout with the config props
Storybook : path=/story/ferlab-components-filters-rangefilter--with-no-data-checkbox
...

feat: move RangeFilter noDataInputOption into config instead of props

---

packages/ui/Release.md
packages/ui/package.json
packages/ui/themes/default/_antd.scss

- closes #FLUI-72
[JIRA LINK]
...

fix: FLUI-72 fixed breaking css change from antd update

---

packages/ui/Release.md
packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/components/filters/types.ts
packages/ui/src/data/filters/utils.ts

- closes [FLUI-76](https://ferlab-crsj.atlassian.net/browse/FLUI-76)
The option to display or hide the no data checkbox in a range filter exists but it's not taking into account so I have added it to getFilterGroup to hide the checkbox.
...

feat(filter): FLUI-76 add no data option to range filter config

---

packages/ui/Release.md
packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/components/filters/RangeFilter.tsx
packages/ui/src/components/filters/constants.ts
packages/ui/src/components/filters/types.ts
packages/ui/src/data/filters/utils.ts

- closes [FLUI-77](https://ferlab-crsj.atlassian.net/browse/FLUI-77)
Add a props to be able to custom the number of decimal in the actual interval display in a range filter.
...

feat(range filter): FLUI-77 add interval decimal

---

packages/ui/package.json
packages/ui/src/layout/ResizableGridLayout/ResizableGridCard/index.tsx

- closes #[698](https://d3b.atlassian.net/browse/SKFP-698)
1. L’item « Download data » devrait être Sentence case
2. Le nom des fichier générés pour le TSV devrait dontenir data au lieu de chart
3. Le nom des images contiennent deux fois l’extension

fix(resizablegrid): SKFP-698 fix file name and typo

---

packages/ui/Release.md
packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/components/AnchorMenu/index.tsx
packages/ui/src/pages/EntityPage/EntityPage.tsx
storybook/stories/Components/AnchorMenu/AnchorMenu.stories.tsx

- closes [FLUI-74](https://ferlab-crsj.atlassian.net/browse/FLUI-74) / [SJIP-511](https://d3b.atlassian.net/browse/SJIP-511)
When you scroll in an entity page with anchor menu, the menu highlight need to follow the scroll.
We add a comment to explain the workaround choose for this fix.
The documentation is [here](https://github.com/ant-design/ant-design/blob/4.x-stable/components/anchor/Anchor.tsx).
The issue is this part of antd code because if getContainer is a function like we had before we return.
[Screencast from 06-29-23 15:20:31.webm](https://github.com/Ferlab-Ste-Justine/ferlab-ui/assets/133775440/c24f0f31-6f9d-48a6-a9dc-abc59fed2af9)
[Screencast from 06-29-23 15:18:53.webm](https://github.com/Ferlab-Ste-Justine/ferlab-ui/assets/133775440/27177f41-5440-4f6b-9784-a9259de4fa5b) …

fix(anchor menu): FLUI-74 / SJIP- 511 fix scroll page

---

packages/ui/Release.md
packages/ui/package.json
packages/ui/src/view/v2/GridCard/GridCard.tsx

- closes #CLIN-2050
GridCard props type was preventing CLIN to build when specifying JSX.Element as part of the `content` props
[JIRA LINK]
Shouldn't have any effect on the app but should statisfy compiler when building projects using GridCard component
...

fix: CLIN-2050 GridCard type fixed content

---

packages/ui/Release.md
packages/ui/package.json
packages/ui/src/data/sqon/utils.ts

- closes #[79](https://ferlab-crsj.atlassian.net/browse/FLUI-79)
Ajout de la notion des nesteds components dans le query builder. Dans CLIN, un pivot était forcé sur [certaines query](https://github.com/Ferlab-Ste-Justine/clin-portal-ui/blob/af73fd9c8fd11fde43646d91c7a1016066ae0ec8/src/views/Snv/utils/helper.ts#L35-L35). Maintenant, il suffit de passer la liste des extends mappings. On y detecte les champs "nested" et ajoute le premier pivot qu'on trouve un champs considéré comme nested.
**Attention: il afin de normalizer nos types, il faut s'assure que VariantMapping est un `IExtendedMappingResults`**
```
import { IExtendedMappingResults } from '@ferlab/ui/core/graphql/types';
...
const variantResolvedSqon = resolveSyntheticSqon(queryList, activeQuery, variantMapping);
```

feat(sqon): FLUI-79 add pivot for nested sqon

---

packages/ui/Release.md
packages/ui/package.json
packages/ui/src/components/ProTable/Header/index.module.scss
packages/ui/src/components/ProTable/Header/index.tsx
packages/ui/src/components/ProTable/index.tsx
packages/ui/src/components/ProTable/types.ts

- closes #CLIN-2207
Ajoute la possibilité d'ajouter plus d'info a droite du nombre de résultat
[[JIRA LINK]](https://ferlab-crsj.atlassian.net/browse/CLIN-2207)
...

feat: CLIN-2207 ajout extraCountInfo header protable

---

packages/ui/Release.md
packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/components/Consequences/Cell/index.module.scss
packages/ui/src/components/Consequences/Cell/index.test.tsx
packages/ui/src/components/Consequences/Cell/index.tsx
packages/ui/src/components/Consequences/Icons/HighBadgeIcon.tsx
packages/ui/src/components/Consequences/Icons/LowBadgeIcon.tsx
packages/ui/src/components/Consequences/Icons/ModerateBadgeIcon.tsx
packages/ui/src/components/Consequences/Icons/ModifierBadgeIcon.tsx
storybook/stories/Components/Consequences/Cell/ConsequencesCell.stories.tsx

- closes #[850](https://d3b.atlassian.net/browse/SKFP-850)
Since both Include and Kids-First use ConsequencesCell and there was bugfix to be done, I decided to port them on the ferlab-ui to prevent multi-code maintenance on both side.

feat(consequence): skfp-850 add consequences cell component

---

packages/ui/Release.md
packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/components/UploadIds/utils.tsx

[SJIP-582](https://d3b.atlassian.net/browse/SJIP-582)
Extract method for multiple projects.
N/A
N/A

fix(upload): SJIP-582 extract upload values

---

packages/ui/Release.md
packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/components/filters/FilterSelector.tsx
packages/ui/src/components/filters/RangeFilter.tsx

[SKFP-831](https://d3b.atlassian.net/browse/SKFP-831)
Display no data option in query pill dropdown in query builder according to filter group options.

fix(filter): SKFP-831 manage no data in QB for range filter

---

packages/ui/Release.md
packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/layout/ResizableGridLayout/index.tsx

Si on resize le browser alors que la grille n'est pas encore chargé, la config peut se corrompe.
https://github.com/Ferlab-Ste-Justine/ferlab-ui/assets/65532894/d269f192-1ee7-44bf-a51d-2894d8bd479d
https://github.com/Ferlab-Ste-Justine/ferlab-ui/assets/65532894/aee32319-e131-4c8a-b9eb-86af5762d622

fix(grid): SKFP-852 prevent save while the grid is still loading

---

packages/ui/Release.md
packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/layout/ResizableGridLayout/index.tsx

Le système de breakpoint custom n'est plus utile avec les derniers fix. Il causait aussi un problème qui corrompait la config lors d'un premier chargement
https://github.com/Ferlab-Ste-Justine/ferlab-ui/assets/65532894/4cb3a242-0db3-4b6b-b729-f89fe3a64f9f
https://github.com/Ferlab-Ste-Justine/ferlab-ui/assets/65532894/690eb9a1-4078-47b5-8ac0-f156a743a89d

fix(grid): SKFP-852 remove breakpoint, rgl should manage it by himself

---

packages/ui/Release.md
packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/view/v2/GridCard/Gridcard.module.scss

- closes #[858](https://d3b.atlassian.net/browse/SKFP-858)
Mouse over is cuttoff on the border of each card
https://github.com/Ferlab-Ste-Justine/ferlab-ui/assets/65532894/1a09b7fe-0104-4405-aab9-523a40cd1f0a
https://github.com/Ferlab-Ste-Justine/ferlab-ui/assets/65532894/2f374efa-91e2-4b9a-85ca-a848fd252c7e

fix(grid): SKFP-858 fix mouseover cutoff

---

packages/ui/Release.md
packages/ui/package.json
packages/ui/src/components/ProTable/types.ts

feat: CQDG-490 ProTable tooltip should be ReactNode
We need to use tooltip in our Table as expected by antd Tooltip title
...

feat: CQDG-490 ProTable tooltip should be ReactNode

---

packages/ui/Release.md
packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/components/ProTable/index.module.scss
packages/ui/src/components/ProTable/index.tsx
packages/ui/src/components/ProTable/types.ts
packages/ui/src/components/tables/ExpandableTable/index.module.scss
packages/ui/src/components/tables/ExpandableTable/index.tsx
storybook/stories/Components/Tables/ProTable/ProTable.stories.tsx

https://ferlab-crsj.atlassian.net/browse/CQDG-490
Exemple d'utilisation:
```
{
key: 'age_at_recruitment',
dataIndex: 'age_at_recruitment',
sorter: { multiple: 1 },
title: intl.get('entities.participant.age'),
popoverProps: {
className: styles.tooltip,
title: <b>{intl.get('entities.participant.age_at_recruitment')}</b>,
content: ageCategories.map((category) => (
<div key={category.key}>
<b>{category.label}:</b>
{` ${category.tooltip}`}
<br />
</div>
)),
},
```

feat: CQDG-490 Add Popover on ProTable title

---

packages/ui/Release.md
packages/ui/jest.setup.js
packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/components/AuthorizedStudies/AuthorizedStudiesListItem.module.scss
packages/ui/src/components/AuthorizedStudies/AuthorizedStudiesListItem.test.tsx
packages/ui/src/components/AuthorizedStudies/AuthorizedStudiesListItem.tsx
packages/ui/src/components/AuthorizedStudies/FencesAuthentificationModal.module.scss
packages/ui/src/components/AuthorizedStudies/FencesAuthentificationModal.test.tsx
packages/ui/src/components/AuthorizedStudies/FencesAuthentificationModal.tsx
packages/ui/src/components/AuthorizedStudies/index.module.scss
packages/ui/src/components/AuthorizedStudies/index.test.tsx
packages/ui/src/components/AuthorizedStudies/index.tsx
packages/ui/src/components/ExternalLink/index.tsx
packages/ui/src/components/PopoverContentLink/index.module.scss
packages/ui/src/components/PopoverContentLink/index.tsx
packages/ui/src/layout/ResizableGridLayout/ResizableGridCard/index.module.scss
packages/ui/src/layout/ResizableGridLayout/ResizableGridCard/index.tsx
packages/ui/src/utils/numberUtils.ts
packages/ui/src/view/v2/GridCard/GridCardConnectPlaceholder.module.scss
packages/ui/src/view/v2/GridCard/GridCardConnectPlaceholder.tsx
packages/ui/src/view/v2/GridCard/GridCardHeader/GridCardConnectPlaceholder.test.tsx
packages/ui/src/view/v2/GridCard/GridCardHeader/GridCardHeader.module.scss
packages/ui/src/view/v2/GridCard/GridCardHeader/index.tsx
packages/ui/themes/default/_theme.template.scss
storybook/stories/Components/AuthorizedStudies/AuthorizedStudies.stories.tsx

- closes #[874](https://d3b.atlassian.net/browse/SKFP-874)
As a user with an eRA Commons login, I want to view and manage my access to controlled access studies in the Kids First (KF) data portal. Associated Registered/open access files will also be included for the controlled access studies that have both. The goal is to simplify the code complexity associated with retrieving data displayed on the front-end by pulling directly from the backend. In hopes to facilitate the handling of this issue: SKFP-868: [Authorized Studies] NCI Fence Issues
BACKLOG
**Widget Title and Information:**
The widget title should display the number of controlled access studies accessible by the user.
An information icon popover should provide details about accessing controlled data with an eRA Commons account. …

feat(studies): SKFP-874 export authorized studies widget to ferlab

---

packages/ui/Release.md
packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/components/QueryBuilder/Combiner.tsx

- closes [#FLUI-116](https://ferlab-crsj.atlassian.net/jira/software/c/projects/FLUI/boards/7?selectedIssue=FLUI-116)
[[JIRA LINK]](https://ferlab-crsj.atlassian.net/jira/software/c/projects/FLUI/boards/7?selectedIssue=FLUI-116)

fix: FLUI-116 fix the operator tooltip in QueryBuild to be on a single line

---

packages/ui/Release.md
packages/ui/jest.setup.js
packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/components/PopoverContentLink/index.tsx
packages/ui/src/components/Widgets/AuthorizedStudies/AuthorizedStudiesListItem.module.scss
packages/ui/src/components/Widgets/AuthorizedStudies/AuthorizedStudiesListItem.test.tsx
packages/ui/src/components/Widgets/AuthorizedStudies/AuthorizedStudiesListItem.tsx
packages/ui/src/components/Widgets/AuthorizedStudies/index.test.tsx
packages/ui/src/components/Widgets/AuthorizedStudies/index.tsx
packages/ui/src/components/Widgets/Cavatica/CavaticaAnalyse.test.tsx
packages/ui/src/components/Widgets/Cavatica/CavaticaAnalyse.tsx
packages/ui/src/components/Widgets/Cavatica/CavaticaAnalyseModal.test.tsx
packages/ui/src/components/Widgets/Cavatica/CavaticaAnalyzeModal.tsx
packages/ui/src/components/Widgets/Cavatica/CavaticaCreateProjectModal.test.tsx
packages/ui/src/components/Widgets/Cavatica/CavaticaListItem.test.tsx
packages/ui/src/components/Widgets/Cavatica/index.test.tsx
packages/ui/src/components/Widgets/Cavatica/index.tsx
packages/ui/src/pages/EntityPage/EntityTableRedirectLink/index.tsx
packages/ui/themes/default/_antd.scss
storybook/package-lock.json
storybook/package.json
storybook/stories/Components/AuthorizedStudies/AuthorizedStudies.stories.tsx

- closes #704
[[JIRA LINK]](https://d3b.atlassian.net/browse/SJIP-704)
Includee ne supporte qu'une seule fence, donc afin d'éviter une modal inutile, si on envoie qu'un seul service à l'authorized studies widget, la connection se fera directement au clique sur bouton

fix: SJIP-704 directly connect the user if only one service is provided to authorized studies widget

---

packages/ui/Release.md
packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/components/Widgets/AuthorizedStudies/AuthorizedStudiesListItem.module.scss
packages/ui/src/components/Widgets/AuthorizedStudies/AuthorizedStudiesListItem.tsx

- closes [#SKFP-964](https://d3b.atlassian.net/jira/software/c/projects/SKFP/boards/82?selectedIssue=SKFP-964)
This fixes Point 1 and Point 2.c
Point 1:
Point 2.c (on voit pas mon curseur mais il hover le nombre de fichier):

fix: SKFP-964 Various visual bugs on Authorized Studies Widget

---

packages/ui/Release.md
packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/pages/EntityPage/EntityDescriptions/index.test.tsx
packages/ui/src/pages/EntityPage/EntityDescriptions/index.tsx

[SJIP-710](https://d3b.atlassian.net/browse/SJIP-710)
- if no descriptions display empty component

fix(entity description): SJIP-710 manage empty descriptions

---

packages/ui/Release.md
packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/components/tables/ExpandableCell/index.module.scss

- closes #[128](https://ferlab-crsj.atlassian.net/browse/FLUI-128)
L'underline se fait surchargé par la classe Typography dans les projets clients.
https://ferlab-crsj.atlassian.net/browse/FLUI-128

Fix/fl UI 128

---

packages/ui/Release.md
packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/pages/EntityPage/EntityConditionsCell/InheritanceTag.tsx

- closes #[1003](https://d3b.atlassian.net/browse/SKFP-1003)
Dans le tableau Gene - Phenotype Association de la page Variant Entity, le tag “Not Applicable” s’affiche mal.
[[JIRA LINK]](https://d3b.atlassian.net/browse/SKFP-1003)

fix(tag): SKFP-1003 fix not applicable tag

---

packages/ui/Release.md
packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/pages/EntityPage/EntityStatistics/index.tsx

- closes #[773](https://d3b.atlassian.net/browse/SJIP-773)
Modify the charts to not show results that are at 0. Only show the bar with values >1 
[[JIRA LINK](https://d3b.atlassian.net/browse/SJIP-773)]

feat(statistic): SJIP-773 add excludeZeroValue to statistic graph

---

packages/ui/Release.md
packages/ui/package.json
packages/ui/src/components/StatisticIcon/index.module.scss
packages/ui/src/components/StatisticIcon/index.tsx

- closes #[TICKET_NUMBER](https://d3b.atlassian.net/browse/SJIP-771)
Afin de permettre de boutons en disabled alors qu'ils contiennent des statisticIcon, quelques modifications ont du être faite.
[[JIRA LINK]](https://d3b.atlassian.net/browse/SJIP-771)

fix(statiticIcon): SJIP-771 fix style

---

packages/ui/Release.md
packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/components/Widgets/AuthorizedStudies/index.test.tsx
packages/ui/src/components/Widgets/AuthorizedStudies/index.tsx
packages/ui/src/components/Widgets/Cavatica/index.tsx
packages/ui/src/components/Widgets/widget.module.scss

- closes #[783](https://d3b.atlassian.net/browse/SJIP-783)
sers cannot get rid of this error message since there is no disconnect button to clear your tokens in key manager. Therefore, we will add update this sentence in the Connection error message: Please refresh the page or disconnect your account and try again.
“We are currently unable to connect to this service. Please refresh the page or [disconnect](http://test/) your account and try again. If the problem persists, please [contact support](http://test/)”
The disconnect button will act the same as when the user successfully connects (same colors/designs)
Upon clicking the disconnect button, it will bring you back to the Disconnected state of the Cavatica widget and will clear the tokens within key manager.
Other minor adjustments to …

fix(widget): SJIP-783 add disconnect btn to error message

---

packages/ui/Release.md
packages/ui/package.json
packages/ui/src/components/Widgets/AuthorizedStudies/index.tsx
packages/ui/src/components/Widgets/Cavatica/index.tsx
packages/ui/src/components/Widgets/widget.module.scss

- closes #[796](https://d3b.atlassian.net/browse/SJIP-796)
The disconnect button is no longer visible in the Authorized Studies widget once a user is connected.
Open image-20240411-174903.png
image-20240411-174903.png
[[JIRA LINK]](https://d3b.atlassian.net/browse/SJIP-796)
...

fix(widget): SJIP-798 fix disconnect btn display

---

packages/ui/Release.md
packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/components/Widgets/Cavatica/CavaticaAnalyse.tsx
packages/ui/src/components/Widgets/Cavatica/CavaticaAnalyzeModal.tsx
packages/ui/src/components/Widgets/Cavatica/type.ts
storybook/stories/Components/Cavatica/Cavatica.stories.tsx

- closes #[758](https://d3b.atlassian.net/browse/SJIP-758)
In order to let users know that their operation is in progress, add a loader to the active “copy files” button when copying files to Cavatica
[[JIRA LINK]](https://d3b.atlassian.net/browse/SJIP-758))
*I slowed down my network and desactivate the modal reset to show the reload state*
[Peek 2024-04-17 13-06.webm](https://github.com/Ferlab-Ste-Justine/ferlab-ui/assets/65532894/4a27a46f-9a45-42ab-84a2-c8dec598908b)

feat(cavatica): SJIP-758 add loading state for copy cavatica files

---

packages/ui/Release.md
packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/components/QueryBuilder/Header/Tools/index.tsx
packages/ui/src/components/QueryBuilder/types.ts

[SJIP-819](https://d3b.atlassian.net/browse/SJIP-819)
- Add tooltips on share and save actions

fix(query builder): SJIP-819 add tooltips

---

packages/ui/Release.md
packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/components/SidebarMenu/index.tsx

[SKFP-1079](https://d3b.atlassian.net/browse/SKFP-1079)
- if the user click on search icon in Sidebar the QF must be opened
see in the ticket
https://github.com/Ferlab-Ste-Justine/ferlab-ui/assets/133775440/3cda2748-1c26-4fd4-8054-6ef9e8e39bf1

fix(quick filter): SKFP-1079 click QF from sidebar 

---

packages/ui/Release.md
packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/components/SidebarMenu/QuickFilter/index.module.scss
packages/ui/src/components/SidebarMenu/QuickFilter/index.tsx

[SKFP-1108](https://d3b.atlassian.net/browse/SKFP-1108)
[SKFP-1109](https://d3b.atlassian.net/browse/SKFP-1109)
[SKFP-1112](https://d3b.atlassian.net/browse/SKFP-1112)
- clear style button
- all/none style actions
- suggestion list max height
- SKFP-1108
hover
- SKFP-1109
Level 1
Level 2
- SKFP-1112
hover

fix(quick filter): SKFP-1108 SKFP-1109 SKFP-1112

---

packages/ui/Release.md
packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/components/OntologyTreeFilter/OntologyTree.test.tsx
packages/ui/src/components/OntologyTreeFilter/OntologyTree.tsx
packages/ui/src/components/OntologyTreeFilter/OntologyTreeTitle.test.tsx
packages/ui/src/components/OntologyTreeFilter/OntologyTreeTitle.tsx
packages/ui/src/components/OntologyTreeFilter/index.module.scss
packages/ui/src/components/OntologyTreeFilter/index.test.tsx
packages/ui/src/components/OntologyTreeFilter/index.tsx
packages/ui/src/components/OntologyTreeFilter/type.ts
packages/ui/src/components/OntologyTreeFilter/utils.test.tsx
packages/ui/src/components/OntologyTreeFilter/utils.tsx
packages/ui/src/components/filters/FilterSelector.tsx
packages/ui/src/components/filters/types.ts
storybook/stories/Components/OntologyTreeModal/OntologyTreeModal.stories.tsx

- closes #[822](https://d3b.atlassian.net/browse/SJIP-822)
- Refacto complète du HPO Browser afin d'être côté ferlab. 
- Feat: On ne highlight plus les mots complets mais uniquement la partie concernant la recherche
- Fix: Le count était faux, il affiche maintenant le nombre uniques de phenotypes/diagnoses au lieu du nombre totale de liason
- Fix:La recherche affiche le bon nombre de résultat, wording changé pour unique diagnosis(diagnoses) et unique phenotype(s)
- Feat: On peut désélectionner le noeud courant et sync avec la liste
- Fix: https://d3b.atlassian.net/browse/SJIP-406
- Feat: Changement du loading pour un skeleton
- Feat: Changement du wording pour unique phenotypes ou unique diagnoses
[[JIRA LINK]](https://d3b.atlassian.net/browse/SJIP-822)

Feat/sjip 822/ontology tree port

---

packages/ui/Release.md
packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/components/PopoverContentLink/index.module.scss

- closes [#SKFP-1096](https://d3b.atlassian.net/browse/SKFP-1096)

fix: SKFP-1096 use default link hover color from theme

---

packages/ui/Release.md
packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/components/QueryBuilder/Header/Tools/QueryBuilderHeaderTools.module.scss
packages/ui/src/components/QueryBuilder/Header/index.module.scss
packages/ui/themes/default/_mixins.scss

- Use a mixin to make override easier QueryBuilder action buttons
- Adjust style selector to only match the targeted element
[[JIRA LINK]](https://ferlab-crsj.atlassian.net/browse/CLIN-2635)

fix: clin-2635 fix styles for text-buttons (:focus-visible, :hover, active)

---

packages/ui/Release.md
packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/components/QueryBuilder/QueryPills/FieldQueryPill.tsx
packages/ui/src/components/QueryBuilder/QueryValues.tsx

- closes #[135](https://ferlab-crsj.atlassian.net/browse/FLUI-135)
N’affiche pas le bon signe dans la QueryValue.  Les différentes valeurs devrait être séparer par un & au lieu d’une , lorsque l’opérateur « All of » est utilisé
[JIRA LINK]

feat(queryValue): FLUI-135 use a different separator for operator All Of

---

packages/ui/Release.md
packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/components/Charts/Bar/index.tsx
storybook/package-lock.json
storybook/stories/Components/Chart/bar.stories.tsx

- closes #[1134](https://d3b.atlassian.net/browse/SKFP-1134)
Explore the adjustment to the bar chart parameter that auto-adjusts the parameter width of the Bar charts. To avoid, one very large bar, we will turn off the auto-adjust parameter for the width to maintain the original size based on original # of items in the x-axis. To be done across CQDG, KF, and INCLUDE
[[JIRA LINK]](https://d3b.atlassian.net/browse/SKFP-1134)

fix(chart): SKFP-1134 adjust bar padding for smaller dataset

---

packages/ui/Release.md
packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/components/OntologyTreeFilter/OntologyTree.tsx
packages/ui/src/components/OntologyTreeFilter/utils.test.tsx
packages/ui/src/components/OntologyTreeFilter/utils.tsx

- closes #[1172](https://d3b.atlassian.net/browse/SKFP-1172)
- Taper « 000 » fait planter l’application. Dans Include, ça ne plante pas. 
- Une recherche va changer pour matching results au lieu de uniques phenotypes (ou diagnoses)
[[JIRA LINK]](https://d3b.atlassian.net/browse/SKFP-1172)
https://github.com/Ferlab-Ste-Justine/ferlab-ui/assets/65532894/1d6e6cc6-e1bc-4d56-9e60-aeeb5d665651
https://github.com/Ferlab-Ste-Justine/ferlab-ui/assets/65532894/a12d7975-71b6-4154-90f8-53ea741b0fb3

fix(ontology): SKFP-1172 improve performance for big dataset

---

.github/workflows/npm_release.yml
.github/workflows/npm_release_cadidate.yml

- closes #FLUI-137
Afin de supporter un retro compatibilité avec la version 9, lorsque un changement doit être sur la version courrante et 9. Nous volons que le script publie sur npm les versions (release, release-candidate)
Critères d’acceptance
lorsque je fais un pull request sur la branch ui-v9 avec une nouvelle version 9.x.x, je dois publier sur npm un  nouvelle ‘release’ sur merge
lorsque je fais un pull request sur la branch ui-v9 avec un nouvelle version. 9.x.x-rcX, je dois publier un nouvelle ‘release-candidate’ on code push

feat: FLUI-137 publish release enable for ui-v9 branch

---

packages/ui/Release.md
packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/components/Assignments/AssignmentsFilter/index.module.css
packages/ui/src/components/Assignments/AssignmentsFilter/index.tsx
packages/ui/src/components/filters/CheckboxFilter/CheckboxFilter.module.css

FIX: CLIN-2868 use a link button to reset assignement filter to be iso with other default filters)
- also fix 'more items' button of facets filters style to have the correct width on focus-visible
https://ferlab-crsj.atlassian.net/browse/CLIN-2868

fix: clin-2868 use a link button to reset assignement filter to be iso with other default filters

---

packages/ui/Release.md
packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/pages/CommunityPage/CommunityMemberProfile.test.tsx
packages/ui/src/pages/CommunityPage/CommunityMemberProfile.tsx
packages/ui/src/pages/CommunityPage/CommunityMemberProfilePage.test.tsx
packages/ui/src/pages/CommunityPage/CommunityMemberProfilePage.tsx

- closes #[374](https://d3b.atlassian.net/browse/SKFP-374)
On affiche directement les valeurs de roles et interests, un mapping value/label devrait être utiliser a la place
[[JIRA LINK]](https://d3b.atlassian.net/browse/SKFP-374)

fix(community): SKFP-374 fix roles and interests display

---

packages/ui/Release.md
packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/components/filters/CheckboxFilter/CheckboxFilter.module.css

- closes #[TICKET_NUMBER](https://d3b.atlassian.net/browse/SKFP-1190)
Les boutons “Clear” et “Apply” devraient être à droite.
[[JIRA LINK]](https://d3b.atlassian.net/browse/SKFP-1190)

fix(filter): SKFP-1190 fix apply button alignment

---

packages/ui/Release.md
packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/components/QueryBuilder/Header/Tools/EditFilterModal.tsx
packages/ui/src/components/QueryBuilder/types.ts
storybook/stories/Components/QueryBuilder/QueryBuilder.stories.tsx

- closes [CQDG-830](https://ferlab-crsj.atlassian.net/browse/CQDG-830)
The backend (Users-api) is restricting some characters when naming Sets and Filters. Front-end should do the same. User has no idea why saving the Set or Filter fails at the moment.   
[JIRA LINK](CQDG-830)
...
[CQDG-830]: https://ferlab-crsj.atlassian.net/browse/CQDG-830?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: CQDG-830 Pattern for name of Sets and Filters

---

packages/ui/Release.md
packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/pages/EntityPage/EntityVariantSummary/index.module.css
packages/ui/src/pages/EntityPage/EntityVariantSummary/index.tsx
storybook/stories/Pages/EntityPage/EntityVariantSummary.stories.tsx

- closes #[131](https://ferlab-crsj.atlassian.net/browse/FLUI-131)
Add a new border property to the Descriptions Basic component (see [this FerLab ticket](https://ferlab-crsj.atlassian.net/browse/FLUI-131))
[[JIRA LINK]](https://ferlab-crsj.atlassian.net/browse/FLUI-131)

feat(description): add basic-bordered theme for variant entity summary

---

packages/ui/Release.md
packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/pages/EntityPage/EntityVariantSummary/index.module.css
packages/ui/src/pages/EntityPage/EntityVariantSummary/index.tsx

- closes #[TICKET_NUMBER](https://d3b.atlassian.net/browse/SKFP-1094)
la composante descriptions n’est pas conform à la maquette. Les éspaces verticaux sont trop large. SVP voir le ticket ferlab en référence et les maquettes.
[[JIRA LINK]](https://d3b.atlassian.net/browse/SKFP-1094)

fix(FLUI-131): fix basic-bordered theme for description

---

packages/ui/Release.md
packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/components/SidebarMenu/QuickFilter/index.module.css

- closes #[TICKET_NUMBER](https://d3b.atlassian.net/browse/SKFP-1235)
The apply and clear button are not well aligned. Update the alignment based on the figma design:
[[JIRA LINK]](https://d3b.atlassian.net/browse/SKFP-1235)

fix(quickfilter): SKFP-1235 fix apply button for level 2 quick filter

---

packages/ui/Release.md
packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/components/SidebarMenu/QuickFilter/index.module.css
packages/ui/themes/default/theme.template.css

- closes #[TICKET_NUMBER](https://d3b.atlassian.net/browse/SJIP-952)
Permet de modifier la couleur des facets btn selon le theme
[[JIRA LINK]](https://d3b.atlassian.net/browse/SJIP-952)

fix(quickfilter): SJIP-952 allow quick filter button facet color theme

---

packages/ui/Release.md
packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/components/Flag/FlagDropdown/index.tsx
packages/ui/src/components/Flag/utils.test.tsx
packages/ui/src/components/Flag/utils.tsx

- closes #CLIN-3220
[JIRA LINK](https://ferlab-crsj.atlassian.net/browse/CLIN-3220)
...

fix: CLIN-3220 sort flag history

---

packages/ui/Release.md
packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/components/Charts/ScatterPlot/Canvas/Layers/MarkerCanvasLayer.tsx
packages/ui/src/components/Charts/ScatterPlot/index.module.css
packages/ui/src/components/Charts/SwarmPlot/index.module.css

- closes #[TICKET_NUMBER](https://d3b.atlassian.net/browse/SJIP-954)
Réduire la marge avec la haut des graphiques
[[JIRA LINK]](https://d3b.atlassian.net/browse/SJIP-954)

fix(scatter): SJIP-954 adjust marker layer annotation position

---

packages/ui/package.json
packages/ui/src/components/filters/RangeFilter.tsx
packages/ui/src/components/filters/types.ts
packages/ui/src/data/filters/Range.ts
packages/ui/src/data/filters/utils.ts
storybook/package-lock.json
storybook/stories/Components/Filters/RangeFilter.stories.tsx

- closes #FLUI-61
https://ferlab-crsj.atlassian.net/browse/FLUI-61
How to use it in project:
https://github.com/include-dcc/include-portal-ui/pull/742
https://github.com/user-attachments/assets/2abf9570-5c26-494c-af82-1812e0329dc6

feat: flui-61 rangefilter default values

---

packages/ui/Release.md
packages/ui/package.json
packages/ui/src/components/ProLabel/index.tsx
storybook/stories/Components/Labels/ProLabel.stories.tsx
storybook/stories/Components/QueryBuilder/QueryBuilder.stories.tsx

- relates to CLIN-2923
Make ProLabel supports Popover and Tooltip for the info icon.
[[JIRA LINK]](https://ferlab-crsj.atlassian.net/browse/CLIN-2923)
- [ x] Storybook add or modified
- [ x] version Update in package.json and Release.md

feat: improve pro label

---

packages/ui/Release.md
packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/components/filters/CheckboxFilter/CheckboxFilter.tsx
packages/ui/src/components/filters/ToggleFilter.module.css
packages/ui/src/components/filters/ToggleFilter.tsx

[FLUI-144](https://ferlab-crsj.atlassian.net/browse/FLUI-144)
Add category icon on toggle filter
- Add icon on boolean facet
[FLUI-144]: https://ferlab-crsj.atlassian.net/browse/FLUI-144?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(facet): FLUI-144 add category icon in toggle facet

---

packages/ui/Release.md
packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/components/UploadIds/UploadModal/index.tsx

- Closes SJIP-1091
With textTransform props, the transformed text was displayed instead of the raw input
- [JIRA](https://d3b.atlassian.net/browse/SJIP-1091)

fix(uploads): SJIP-1091 display raw input for unmatch list

---

packages/ui/Release.md
packages/ui/package.json
packages/ui/src/components/Widgets/Cavatica/CavaticaCreateProjectModal.module.css
packages/ui/src/components/Widgets/Cavatica/CavaticaCreateProjectModal.tsx

- Closes SKFP-1057
Dans la modal de création de projet Cavatica, retirer les tooltips gris du browser.
Vu dans Safari et Chrome.
- [JIRA](https://ferlab-crsj.atlassian.net/browse/SKFP-1057)

fix(cavatica): SKFP-1057 remove native tooltips for label and input

---

packages/ui/Release.md
packages/ui/package.json
packages/ui/src/components/Assignments/AssignmentsSelect/index.tsx
packages/ui/src/components/Assignments/AssignmentsTag/index.tsx

- Closes PRESC-341
- [JIRA](https://ferlab-crsj.atlassian.net/browse/PRESC-341)
1. 
2.

feat: PRESC-341 option show ldm assigment

---

packages/ui/Release.md
packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/components/filters/types.ts
storybook/package-lock.json

[FLUI-61](https://ferlab-crsj.atlassian.net/browse/FLUI-61)
Make min and max properties not required in default range operator.
Be able to define default operator without define min and max
[FLUI-61]: https://ferlab-crsj.atlassian.net/browse/FLUI-61?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(facet): FLUI-61 min and max not required for default operator

---

packages/ui/Release.md
packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/components/Charts/Venn/index.tsx

Issue: Although the section is disabled with 0 results in the diagram, we can still click it and it will create a checkmark in the checkbox for that section in the table. We shouldn’t be able to check it from the venn diagram
- [JIRA](https://ferlab-crsj.atlassian.net/browse/SJIP-1116)
https://github.com/user-attachments/assets/03e62f71-6dfc-41de-85bd-4ddb572adf64

feat(venn): SJIP-1116 prevent clicking on disabled section

---

packages/ui/Release.md
packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/pages/EntityPage/EntityTitle/index.module.css
packages/ui/src/pages/EntityPage/EntityTitle/index.tsx

[SKFP-1469](https://ferlab-crsj.atlassian.net/browse/SKFP-1469)
Manage title entity display
- Add tooltip and ellipsis on long title in entity

feat(entity): SKFP-1469 manage long title

---

packages/ui/Release.md
packages/ui/package.json
packages/ui/src/components/Charts/Venn/VennModal.tsx
packages/ui/src/components/Charts/Venn/index.tsx
storybook/stories/Components/Chart/venn.stories.tsx

- Closes SJIP-1257
When creating a venn with 2 queries, it caused a shifting of the display. Below are the two queries used. It doesn’t happen all the time but I opened it 5 times and the shifting occurred 2/5 times. 
- [JIRA](https://ferlab-crsj.atlassian.net/browse/SJIP-1257)

fix(venn): SJIP-1257 force static width and height for venn

---

packages/ui/Release.md
packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/pages/EntityPage/EntityCustomContent/index.module.css
packages/ui/src/pages/EntityPage/EntityCustomContent/index.test.tsx
packages/ui/src/pages/EntityPage/EntityCustomContent/index.tsx
packages/ui/src/pages/EntityPage/index.tsx
storybook/package-lock.json
storybook/stories/Pages/EntityPage/EntityCustomContent.stories.tsx

[SJIP-1235](https://ferlab-crsj.atlassian.net/browse/SJIP-1235)
- Add custom content entity panel
- Be able to add collapsable entity panel with custom content
NA

feat(entity): SJIP-1235 add custom content entity

---

packages/ui/Release.md
packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/components/BiospecimenRequest/RequestBiospecimenButton.tsx

[SJIP-1235](https://ferlab-crsj.atlassian.net/browse/SJIP-1235)
Be able to change button size.
- Add size props du request biospecimen button

feat(biospecimen): SJIP-1235 add size props to request biospecimen

---

packages/ui/Release.md
packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/layout/PageHeader/index.module.css
packages/ui/src/layout/PageHeader/index.test.tsx
packages/ui/src/layout/PageHeader/index.tsx
storybook/package-lock.json
storybook/stories/Layout/PageHeader.stories.tsx

[SJIP-1254](https://ferlab-crsj.atlassian.net/browse/SJIP-1254)
Add page header
Add page header with icon, back and subtitle options
NA

feat(pageheader): SJIP-1254 add page header component

---

packages/ui/Release.md
packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/components/Charts/Venn/VennChartWithSelect.tsx
packages/ui/src/components/Charts/Venn/index.module.css
packages/ui/src/components/Charts/Venn/index.tsx
packages/ui/src/components/Charts/Venn/utils.tsx

- Closes SJIP-1299
Add Download PNG feature to Venn Diagram in Data exploration and in Set operations (analytics).
- [JIRA](https://ferlab-crsj.atlassian.net/browse/SJIP-1299)

feat(venn): SJIP-1299 add download button for venn chart

---

packages/ui/Release.md
packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/components/Charts/Venn/index.tsx

[SKFP-1504](https://ferlab-crsj.atlassian.net/browse/SKFP-1504)
Manage somatic variant un Venn diagram
- display somatic icon in both tables
- display the correct tooltip

fix(venn): SKFP-1504 manage somatic in venn

---

packages/ui/Release.md
packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/components/QueryBuilder/QueryTools.tsx

- Closes SJIP-1334
Goal: Currently, the feature for the venn diagram is fairly hidden. A user needs to select 2-3 queries to be able to have the compare button appear. Therefore, we will always display the Compare button even when there is no selection for the queries. Place it betwene the label button and the new query button with the same styling that it currently has
When <2 queries selected:
Maintain the disable state
tooltip: Select 2 or 3 queries to generate a Venn diagram comparison
When >3 queries selected:
Maintain the disable state
tooltip: Only available with 2 or 3 queries selected
When 2 or 3 queries selected:
Active state as it currently is without a tooltip
- [JIRA](https://ferlab-crsj.atlassian.net/browse/SJIP-1334)

feat(querytool): SJIP-1334 always display compare button

---

packages/ui/Release.md
packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/components/ProTable/index.tsx

- Closes SJIP-1336
When using the "Select All Results" option in the table (data Explo, Variant explo), and then manually deselecting a few rows, the "selected" count does not update accordingly.
The select all should be “deactivated” and the selection count should come back to represent the number of rows in the table page. For example in the image below, we have a total of 9431 rows with the Select All, but deselecting 2 rows should “deactivate” the select all and the count should be representative of the page results so it would be 18 items selected (assuming I have a page view of 20).
Problem occurs in all projects
- [JIRA](https://ferlab-crsj.atlassian.net/browse/SJIP-1336)
https://github.com/user-attachments/assets/630e0d5b-a42b-4a34-b571-48566bbb62a8

fix(table): SJIP-1336 fix table behaviour on select all pages

---

packages/ui/Release.md
packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/components/Charts/Venn/VennChartWithFilters/index.tsx
packages/ui/src/components/Charts/Venn/VennChartWithSelect.tsx
packages/ui/src/components/Charts/Venn/VennQueryPill.tsx

Si on sélectionne un set et qu’on compare d’autres données, le set sélectionné reste actif. Le coches devraient se réinitialiser au changement de données.
- [JIRA](https://ferlab-crsj.atlassian.net/browse/)
https://github.com/user-attachments/assets/52852394-3774-4d05-b4da-6c330b6663df

fix(venn): SJIP1356 reset select table set when venn chart is reloaded

---

packages/ui/Release.md
packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/components/Charts/LegendSymbol/index.tsx

- Closes SKFP-1527
When downloading pie charts via the download png of the summary view,  there seems to be missing the accessibility patterns in the legend. Add the same accessbility patterns seen in the pie charts to the legend.
- [JIRA](https://ferlab-crsj.atlassian.net/browse/SKFP-1527)

fix(chart): SKFP-1527 add custom legends with patterns

---

packages/ui/Release.md
packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/components/Widgets/BiospecimenRequests/index.tsx

- Closes SKFP-1530
We will remove the concept of a private saved sets. All sets will be set to public and will be shareable as part of a shared filter. 
Note:
Remove the warning modal after clicking on the share button of the Biospecimen. Upon clicking on the share button, display a toaste
- [JIRA](https://ferlab-crsj.atlassian.net/browse/SKFP-1530)
https://github.com/user-attachments/assets/a3dba23a-1867-4821-a449-9aa3d9ce0060

feat(widget): SKFP-1530 remove warning for request biospecimen

---

packages/ui/Release.md
packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/pages/EntityPage/EntityStatistics/index.tsx
storybook/package-lock.json

[SJIP-1370](https://ferlab-crsj.atlassian.net/browse/SJIP-1370)
Race demographic chart is sliced in download png.
- See the legend

fix(statistics): SJIP-1370 increase demographic legend width

---

packages/ui/Release.md
packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/layout/ResizableGridLayout/ResizableGridCard/index.module.css
packages/ui/src/pages/EntityPage/EntityStatistics/index.tsx

[SJIP-1378](https://ferlab-crsj.atlassian.net/browse/SJIP-1378)
Remove download button in card header
- add props to render download actions optionnal
Always download button.
- withDownload=true
- withDownload=false

feat(statistics): SJIP-1378 render optional download actions

---

packages/ui/Release.md
packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/layout/ResizableGridLayout/ResizableGridCard/index.tsx
packages/ui/src/layout/ResizableGridLayout/utils.ts
packages/ui/src/pages/EntityPage/EntityStatistics/index.tsx

[SJIP-1379](https://ferlab-crsj.atlassian.net/browse/SJIP-1379)
Improve TSV download
- format frequency
- rename first column header
- remove empty column

feat(statistic): SJIP-1379 improve download tsv

---

packages/ui/Release.md
packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/pages/EntityPage/EntityStatistics/index.tsx

[SJIP-1372](https://ferlab-crsj.atlassian.net/browse/SJIP-1372)
Remove HPO and Mondo graphs in public study entity.
Render optionnal HPO and mondo graphs in Stistics entity.
NA

feat(statistics): SJIP-1372 render optionnal hpo and mondo

---

packages/ui/Release.md
packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/layout/ResizableGridLayout/utils.ts

[SJIP-1335](https://ferlab-crsj.atlassian.net/browse/SJIP-1335)
Enrich tree node data
- display multiple values in bar chart tooltip
NA

feat(chart): SJIP-1335 add data in tree node to chart

---

packages/ui/Release.md
packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/components/ProTable/Header/ItemsCount/index.tsx
packages/ui/src/components/ProTable/types.ts
packages/ui/src/pages/CommunityPage/index.test.tsx
packages/ui/src/pages/CommunityPage/index.tsx
storybook/package-lock.json

[SKFP-1537](https://ferlab-crsj.atlassian.net/browse/SKFP-1537)
Add suffix after results in community page
- Add suffix props to pro table dictionnary

feat(table): SKFP-1537 add result suffix to pro table results

---

packages/ui/Release.md
packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/pages/LandingPage/Studies/Summary/index.tsx
packages/ui/src/pages/LandingPage/Studies/index.tsx

- Closes CQDG-1157
On CQDG we need the ghost primary button on this part
- [JIRA](https://ferlab-crsj.atlassian.net/browse/CQDG-1157)

feat: CQDG-1157 add studiesBtnProps on Studies Summary on Landing page
